---
title: "03 - Grade and PTCy Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source(file.path(dirname(getwd()), "config", "config.R"))
source(file.path(dirname(getwd()), "functions", "mlr_functions.R"))

# Load data from previous notebooks
data <- readRDS(file.path(PROCESSED_DATA_PATH, "patient_data_all.rds"))
data_allo <- readRDS(file.path(PROCESSED_DATA_PATH, "patient_data_allo.rds"))
data_nonallo <- readRDS(file.path(PROCESSED_DATA_PATH, "data_nonallo_list.rds"))
data_meta <- readRDS(file.path(PROCESSED_DATA_PATH, "data_meta.rds"))
all_full_allo <- readRDS(file.path(PROCESSED_DATA_PATH, "all_full_allo.rds"))
filenames <- readRDS(file.path(PROCESSED_DATA_PATH, "filenames.rds"))
clinical_data <- readRDS(file.path(PROCESSED_DATA_PATH, "clinical_data_full.rds"))
data_squished <- readRDS(file.path(PROCESSED_DATA_PATH, "data_squished.rds"))
data_squished_w0 <- readRDS(file.path(PROCESSED_DATA_PATH, "data_squished_w0.rds"))
data_allo_squished <- readRDS(file.path(PROCESSED_DATA_PATH, "data_allo_squished.rds"))
data_allo_squished_w0 <- readRDS(file.path(PROCESSED_DATA_PATH, "data_allo_squished_w0.rds"))
data_nonallo_squished <- readRDS(file.path(PROCESSED_DATA_PATH, "data_nonallo_squished.rds"))
data_nonallo_squished_w0 <- readRDS(file.path(PROCESSED_DATA_PATH, "data_nonallo_squished_w0.rds"))
meta_data_clin <- readRDS(file.path(PROCESSED_DATA_PATH, "meta_data_clin.rds"))
meta_data <- readRDS(file.path(PROCESSED_DATA_PATH, "meta_data.rds"))
expanded_clones <- readRDS(file.path(PROCESSED_DATA_PATH, "expanded_clones.rds"))
data_CD48_all <- readRDS(file.path(PROCESSED_DATA_PATH, "data_CD48_all.rds"))
data_CD48_all_expand <- readRDS(file.path(PROCESSED_DATA_PATH, "data_CD48_all_expand.rds"))
patient_data_all <- readRDS(file.path(PROCESSED_DATA_PATH, "patient_data_all_df.rds"))
data_squished_time <- readRDS(file.path(PROCESSED_DATA_PATH, "data_squished_time.rds"))
patient_data_all_2 <- readRDS(file.path(PROCESSED_DATA_PATH, "patient_data_all_2.rds"))
unique_identifiers <- c("cdr3_amino_acid", "v_resolved", "j_resolved")
remove_pat_regx <- ""  # set to e.g. "067|070" to exclude patients
all_rep_div        <- readRDS(file.path(PROCESSED_DATA_PATH, "all_rep_div.rds"))
all_allo_div       <- readRDS(file.path(PROCESSED_DATA_PATH, "all_allo_div.rds"))
all_allo_div_CD4   <- readRDS(file.path(PROCESSED_DATA_PATH, "all_allo_div_CD4.rds"))
all_allo_div_CD8   <- readRDS(file.path(PROCESSED_DATA_PATH, "all_allo_div_CD8.rds"))
all_nonallo_div    <- readRDS(file.path(PROCESSED_DATA_PATH, "all_nonallo_div.rds"))
all_nonallo_div_CD4 <- readRDS(file.path(PROCESSED_DATA_PATH, "all_nonallo_div_CD4.rds"))
all_nonallo_div_CD8 <- readRDS(file.path(PROCESSED_DATA_PATH, "all_nonallo_div_CD8.rds"))
freq_Both_vio_ex   <- readRDS(file.path(PROCESSED_DATA_PATH, "freq_Both_vio_ex.rds"))
```



```{r, fig.height = 8, fig.width=16, dpi = 600}


get_timepoint <- function(df) {
  #' Get earliest post-stimulation timepoints for each patient
  #'
  #' @description This function selects all timepoints less than or equal to 3 and the earliest timepoint greater than 3 for each patient.
  #'
  #' @param df A dataframe containing `timepoint` and `PatientID` columns.
  #' @return A dataframe with the earliest timepoints for each patient.

  df <- df %>%
    mutate(timepoint = strtoi(timepoint)) %>%
    filter(!is.na(timepoint))

  # Select all timepoints less than or equal to 3
  df_res <- df %>%
    filter(timepoint <= 3)

  # For each patient, select the earliest timepoint greater than 3
  df_patients <- df %>%
    group_by(PatientID) %>%
    filter(timepoint > 3) %>%
    filter(timepoint == min(timepoint)) %>%
    ungroup()

  # Combine the selected timepoints
  df_res <- bind_rows(df_res, df_patients)

  return(df_res)
}


get_early_timepoint <- function(df) {
  #' Get earliest and specific early timepoints for each patient
  #'
  #' @description This function selects the earliest timepoint greater than 3 and also specific early timepoints between 2 and 3 for each patient.
  #'
  #' @param df A dataframe containing `timepoint` and `PatientID` columns.
  #' @return A dataframe with the earliest timepoints and specific early timepoints for each patient.

  df_res <- data.frame()

  for (patient in unique(df$PatientID)) {
    # Select earliest timepoint greater than 3 for each patient
    df_pat <- df %>%
      filter(PatientID == patient, timepoint > 3) %>%
      filter(timepoint == min(timepoint))

    # Select timepoints between 2 and 3 for each patient
    df_pat_3 <- df %>%
      filter(PatientID == patient, timepoint >= 2, timepoint <= 3)

    # Combine the selected timepoints
    df_res <- bind_rows(df_res, df_pat, df_pat_3)
  }

  return(df_res)
}



unstim_plot_freqs <- vector("list", 3)
unstim_3_plot_freqs <- vector("list", 3)
early_plot_freqs <- vector("list", 3)
earliest_plot_freqs <- vector("list", 3)
unstim_plot_shannons <- vector("list", 3)
unstim_3_plot_shannons <- vector("list", 3)
early_plot_shannons <- vector("list", 3)
earliest_plot_shannons <- vector("list", 3)
early_plot_n_clones <- vector("list", 3)
early_plot_avg_freqs <- vector("list", 3)

for(rep_div in c("allo", "nonallo", "all")){
  if (rep_div == "allo"){
    i = 1
    rep_title = "Alloreactive"
  }else if(rep_div == "nonallo"){
    i = 2
    rep_title = "Non-Alloreactive"
  }else{
    i = 3
    rep_title = "All"
  }
  patient_data_allo <- dplyr::full_join(patient_data_all, meta_data,  by = "PatientID")%>%
    mutate(timepoint = SampleID)%>%
    select(-c(SampleID))
  colnames(patient_data_allo) <- sapply(colnames(patient_data_allo), function(x){str_replace_all(x, "-", "")})
  patient_data_allo <- patient_data_allo[patient_data_allo$Rep_div == rep_div,]
  patient_data_allo <- patient_data_allo[which(!is.na(patient_data_allo$timepoint)),]
  patient_data_allo[patient_data_allo$timepoint == "MLRCFSElo",]$timepoint  <- "1"
  patient_data_allo[patient_data_allo$timepoint == "unstimulated",]$timepoint  <- "0"
  patient_data_allo_copy <- patient_data_allo%>%
    mutate(timepoint = strtoi(timepoint))
  patient_data_allo_copy <- patient_data_allo_copy[which(!is.na(patient_data_allo_copy$timepoint)),]


  patient_data_allo_copy <- patient_data_allo_copy%>%
    mutate(GVHD_GRADE_1 = ifelse(grepl("Severe", GVHD_GRADE_1), "Severe", GVHD_GRADE_1))%>%
    mutate(GVHD_GRADE_1 = factor(GVHD_GRADE_1, levels = c("No", "Mild", "Severe")))%>%
    replace_na(list(shannons.diversity = 0, shannons.entropy = 0))#%>%
    # mutate(PTCy = ifelse(grepl("PTCy", PTCy), "PTCy", "No PTCy"))

  df_unstimulated <- patient_data_allo_copy[patient_data_allo_copy$timepoint == 0,]%>%
    mutate(timepoint = "Donor")%>%
    filter(PTCy == "PTCy")

  df_unstimulated_all <- patient_data_allo_copy[patient_data_allo_copy$timepoint == 0,]%>%
    mutate(timepoint = "Donor")


  patient_data_allo_copy <- patient_data_allo_copy[patient_data_allo_copy$timepoint > 1,]

  df_early_timepoint_all <- get_early_timepoint(patient_data_allo_copy)%>%
    mutate(timepoint = ifelse(timepoint <= 3, "<= 3", "Earliest Timepoint"))%>%
    mutate(timepoint = factor(timepoint, levels = c("<= 3", "Earliest Timepoint")))%>%
    group_by(PatientID,GVHD_GRADE_1, timepoint)

  df_early_timepoint <- df_early_timepoint_all %>%
    filter(PTCy == "PTCy")

  df_early_timepoint <- df_early_timepoint[df_early_timepoint$PatientID != "R070",]

  data_CD48_all_expand_adj <- dplyr::full_join(data_CD48_all_expand, clinical_data, by = 'PatientID')
  data_CD48_all_expand_adj <- data_CD48_all_expand_adj[!is.na(data_CD48_all_expand_adj$cdr3_amino_acid),]
  data_CD48_all_expand_adj <- data_CD48_all_expand_adj[data_CD48_all_expand_adj$PatientID != "R070",]

  df_timepoint <- get_timepoint(patient_data_allo_copy)%>%
    mutate(timepoint = ifelse(timepoint <= 3 & timepoint >=2, "<= 3", "Earliest Timepoint"))%>%
    mutate(timepoint = factor(timepoint, levels = c("Donor", "<= 3", "Earliest Timepoint")))%>%
    filter(PTCy == "PTCy")

  df_timepoint <- df_timepoint[df_timepoint$PatientID != 70,]


  df_unstimulated_3 <- bind_rows(df_unstimulated%>%filter(PatientID %in% unique(df_timepoint$PatientID)), df_early_timepoint)%>%
    mutate(timepoint = factor(timepoint, levels = c("Donor", "<= 3", "Earliest Timepoint")))%>%
    # filter(GVHD_GRADE_1 != "No")%>%
    group_by(PatientID)%>%
    mutate(n_in = n())%>%
    filter(n_in >= 3)%>%
    ungroup()%>%
    replace_na(list(avg_freq = 0))


  unstim_plot_freq <- ggplot(df_unstimulated_all, aes(x = PTCy, y = cum_freq, fill = PTCy))+
    geom_boxplot()+
    geom_beeswarm(aes(color = GVHD_GRADE_1))+
    scale_color_manual(values = c("#09BB8C", "#005A8F", "#B85000", "grey"))+
    scale_y_continuous(labels = scales::number_format(accuracy = 0.0001))+
    stat_compare_means(comparisons = list(c("PTCy", "No PTCy")), method = "wilcox.test", label = "p.format", hide.ns = FALSE, label.y = quantile(df_unstimulated_all$cum_freq, probs = c(0.9)), size = 12)+
    labs(x = "Timepoint", y = "Frequency", title = paste(rep_title, "Unstimulated"), color = "GVHD Grade")+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"))+
    # expand_limits(y = max(df_unstimulated_all$cum_freq)+.05)+
    theme_pubr()+
    theme(legend.position = "none")


  unstim_3_plot_freq <- ggplot(df_unstimulated_3, aes(x = timepoint, y = cum_freq, shape = PatientID))+
    geom_point(aes(color = GVHD_GRADE_1), size = 6)+
    geom_line(aes(group = PatientID, color = GVHD_GRADE_1), linewidth = 1.5)+
    scale_color_manual(values = c( "#005A8F", "#B85000", "grey"))+
    scale_y_continuous(labels = scales::number_format(accuracy = 0.0001))+
    stat_compare_means(comparisons = list(c("Donor", "<= 3")), method = "wilcox.test", paired = TRUE, label = "p.format", hide.ns = FALSE, group.by = "PatientID", size = 12, label.y = quantile(df_unstimulated_3$cum_freq, probs = c(0.9)))+
    labs(x = "Timepoint", y = "Cumulative Frequency", title = paste(rep_title, "Unstimulated"), color = "GVHD Grade")+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"))+
    # expand_limits(y = max(df_unstimulated_3$cum_freq)+.05)+
    theme_pubr()+
    theme(legend.position = "none")

  earliest_plot_freq <- ggplot(df_early_timepoint_all[df_early_timepoint_all$timepoint == "Earliest Timepoint",], aes(x = PTCy, y = cum_freq, fill = PTCy))+
    geom_boxplot()+
    geom_beeswarm(aes(color = GVHD_GRADE_1))+
    scale_y_continuous(labels = scales::number_format(accuracy = 0.0001))+
    scale_color_manual(values = c("#09BB8C", "#005A8F", "#B85000", "grey"))+
    stat_compare_means(comparisons = list(c("PTCy", "No PTCy")), method = "wilcox.test",label = "p.format", hide.ns = FALSE, label.y = quantile(df_early_timepoint_all$cum_freq, probs = c(0.9)), size = 6)+
    labs(x = "Timepoint", y = "Cumulative Frequency", title = paste(rep_title, "Earliest Timepoint"), color = "GVHD Grade")+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"))+
    # expand_limits(y = max(df_early_timepoint_all$cum_freq)+.05)+
    theme_pubr()+
    theme(legend.position = "none")

  test_res <- wilcox.test(cum_freq ~ timepoint, data = df_unstimulated_3[!grepl("Donor",df_unstimulated_3$timepoint),], paired = TRUE, alternative = "greater")
  print(test_res)

  early_plot_freq <- ggplot(df_unstimulated_3[df_unstimulated_3$timepoint != "Donor",], aes(x = timepoint, y = cum_freq, shape = PatientID))+
    geom_line(aes(group = PatientID, color = GVHD_GRADE_1), linewidth = 1.5)+
    geom_point(aes(color = GVHD_GRADE_1), size = 6)+
    scale_y_continuous(labels = scales::number_format(accuracy = 0.0001))+
    stat_compare_means(comparisons = list(c("<= 3", "Earliest Timepoint")), method = "wilcox.test", paired = TRUE, label = "p.format", hide.ns = FALSE, group.by = "PatientID", method.args = list(alternative = "greater"), size = 12, label.y = quantile(df_unstimulated_3$cum_freq, probs = c(0.9)))+
    scale_color_manual(values = c("#005A8F", "#B85000", "grey"))+
    # expand_limits(y = max(df_timepoint$cum_freq)+.05)+
    labs(x = "Timepoint", y = "Cumulative Frequency", title = rep_title, color = "GVHD Grade")+
    # coord_cartesian(ylim = c(0,0.4))+
    theme_minimal()+
    theme_pubr()+
    theme(legend.position = "none")


  unstim_plot_shannon <- ggplot(df_unstimulated_all, aes(x = PTCy, y = shannons.diversity, fill = PTCy))+
    geom_boxplot()+
    geom_beeswarm(aes(color = GVHD_GRADE_1))+
    scale_color_manual(values = c("#09BB8C", "#005A8F", "#B85000", "grey"))+
    stat_compare_means(comparisons = list(c("PTCy", "No PTCy")), method = "wilcox.test",label = "p.format", hide.ns = FALSE, label.y = quantile(df_unstimulated_all$shannons.diversity, probs = c(0.9)), size = 6)+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"))+
    # expand_limits(y = max(df_unstimulated_all$shannons.diversity)+3)+
    labs(x = "Timepoint", y = "Shannon's Diversity", title = paste(rep_title, "Unstimulated"), color = "GVHD Grade")+
    theme_minimal()+
    theme(plot.title = element_text(size = 18), axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 14), axis.text = element_text(size = 12), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(color = "black"), axis.ticks = element_line(color = "black"),  axis.ticks.length = unit(0.25, "cm"))+
    theme(legend.position = "none")
  #
  unstim_3_plot_shannon <- ggplot(df_unstimulated_3, aes(x = timepoint, y = shannons.diversity, shape = PatientID))+
    geom_beeswarm(aes(color = GVHD_GRADE_1), size = 2)+
    geom_line(aes(group = PatientID, color = GVHD_GRADE_1), linewidth = 1.5)+
    scale_color_manual(values = c("#005A8F", "#B85000", "grey"))+
    scale_y_continuous(labels = scales::number_format(accuracy = 1))+
    stat_compare_means(comparisons = list(c("unstimulated", "<= 3")), method = "wilcox.test", paired = TRUE, label = "p.format", hide.ns = FALSE, group.by = "PatientID", size = 12, label.y = quantile(df_unstimulated_3$shannons.diversity, probs = c(0.9)))+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"))+
    # expand_limits(y = max(df_unstimulated_3$shannons.diversity)+3)+
    labs(x = "Timepoint", y = "Shannon's Diversity", title = paste(rep_title, "Unstimulated"), color = "GVHD Grade")+
    theme_minimal()+
    theme(plot.title = element_text(size = 18), axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 14), axis.text = element_text(size = 12), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.line = element_line(color = "black"), axis.ticks = element_line(color = "black"),  axis.ticks.length = unit(0.25, "cm"))+
    theme(legend.position = "none")

  earliest_plot_shannon <- ggplot(df_early_timepoint_all[df_early_timepoint_all$timepoint == "Earliest Timepoint",], aes(x = PTCy, y = shannons.diversity, fill = PTCy))+
    geom_boxplot()+
    geom_beeswarm(aes(color = GVHD_GRADE_1))+
    scale_color_manual(values = c("#09BB8C", "#005A8F", "#B85000", "grey"))+
    scale_y_continuous(labels = scales::number_format(accuracy = 1))+
    stat_compare_means(comparisons = list(c("PTCy", "No PTCy")), method = "wilcox.test",label = "p.format", hide.ns = FALSE, label.y = quantile(df_early_timepoint_all$shannons.diversity, probs = c(0.90)), size = 12)+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"))+
    # expand_limits(y = max(df_early_timepoint_all$shannons.diversity)+3)+
    labs(x = "Timepoint", y = "Shannon's Diversity", title = paste(rep_title, "Earliest Timepoint"), color = "GVHD Grade")+
    theme_pubr()+
    theme(legend.position = "none")

  # df_early_timepoint <- df_early_timepoint%>%
  #   filter(PatientID %in% unique(df_timepoint$PatientID))
  df_timepoint_ptcy <- df_timepoint%>%filter(PatientID %in% unique(df_timepoint$PatientID))

  early_plot_shannon <- ggplot(df_unstimulated_3[df_unstimulated_3$timepoint != "Donor",], aes(x = timepoint, y = shannons.diversity, shape = PatientID, group = PatientID))+
    geom_line(aes(group = PatientID, color = GVHD_GRADE_1), linewidth = 1.5)+
    geom_point(aes(color = GVHD_GRADE_1), size = 6)+
    scale_y_continuous(labels = scales::number_format(accuracy = 1))+
    stat_compare_means(comparisons = list(c("<= 3", "Earliest Timepoint")), paired = T, label = "p.format", method.args = list(alternative = "greater"), size = 6, label.y = quantile(df_unstimulated_3[df_unstimulated_3$timepoint != "Donor",]$shannons.diversity, probs = c(0.9)))+
    scale_color_manual(values = c( "#005A8F", "#B85000", "grey"))+
    labs(x = "Timepoint", y = "Shannon's Diversity", title = rep_title, color = "GVHD Grade")+
    theme_pubr()+
    theme(legend.position = "right")#, axis.text.x.bottom = element_text(angle = 45, vjust = 0))


  early_plot_n_clone <- ggplot(df_unstimulated_3[df_unstimulated_3$timepoint != "Donor",], aes(x = timepoint, y = n_clone, shape = PatientID))+
    geom_line(aes(group = PatientID, color = GVHD_GRADE_1), linewidth = 1.5)+
    geom_point(aes(color = GVHD_GRADE_1), size = 6)+
    scale_y_continuous(labels = scales::number_format(accuracy = 1))+
    stat_compare_means(comparisons = list(c("<= 3", "Earliest Timepoint")), method = "wilcox.test", paired = TRUE, label = "p.format", hide.ns = FALSE, group.by = "PatientID", method.args = list(alternative = "greater"), size = 6, label.y = quantile(df_unstimulated_3[df_unstimulated_3$timepoint != "Donor",]$n_clone, probs = c(0.90)))+
    scale_color_manual(values = c("#005A8F", "#B85000", "grey"))+
    # expand_limits(y = max(df_timepoint$cum_freq)+.05)+
    labs(x = "Timepoint", y = "# of Clones", title = rep_title, color = "GVHD Grade")+
    # coord_cartesian(ylim = c(0,0.4))+
    theme_minimal()+
    theme_pubr()+
    theme(legend.position = "none")

  early_plot_avg_freq <- ggplot(df_unstimulated_3[df_unstimulated_3$timepoint != "Donor",], aes(x = timepoint, y = avg_freq, shape = PatientID))+
    geom_line(aes(group = PatientID, color = GVHD_GRADE_1), linewidth = 1.5)+
    geom_point(aes(color = GVHD_GRADE_1), size = 6)+
    scale_y_continuous(labels = scales::number_format(accuracy = 0.0001))+
    stat_compare_means(comparisons = list(c("<= 3", "Earliest Timepoint")), method = "wilcox.test", paired = TRUE, label = "p.format", hide.ns = FALSE, group.by = "PatientID", method.args = list(alternative = "greater"), size = 6, label.y = quantile(df_unstimulated_3[df_unstimulated_3$timepoint != "Donor",]$avg_freq, probs = c(0.90)))+
    scale_color_manual(values = c("#005A8F", "#B85000", "grey"))+
    # expand_limits(y = max(df_timepoint$cum_freq)+.05)+
    labs(x = "Timepoint", y = "Average Clone Frequency", title = rep_title, color = "GVHD Grade")+
    # coord_cartesian(ylim = c(0,0.4))+
    theme_minimal()+
    theme_pubr()+
    theme(legend.position = "none")




  # group.by = "PatientID"method = "kruskal.test"
unstim_plot_freqs[[i]] <- unstim_plot_freq
unstim_3_plot_freqs[[i]] <- unstim_3_plot_freq
early_plot_freqs[[i]] <- early_plot_freq
earliest_plot_freqs[[i]] <- earliest_plot_freq
unstim_plot_shannons[[i]] <- unstim_plot_shannon
unstim_3_plot_shannons[[i]] <- unstim_3_plot_shannon
early_plot_shannons[[i]] <- early_plot_shannon
earliest_plot_shannons[[i]] <- earliest_plot_shannon
early_plot_n_clones[[i]] <- early_plot_n_clone
early_plot_avg_freqs[[i]] <- early_plot_avg_freq
}


#
early_plot_freqs[[1]] <-  early_plot_freqs[[1]]+theme(legend.position = "none")
early_plot_freqs[[2]]  <- early_plot_freqs[[2]]+theme(legend.position = "none")
early_plot_shannons[[1]] <- early_plot_shannons[[1]]+theme(legend.position = "none")
legend_for_plot <- cowplot::get_legend(early_plot_shannons[[2]])
early_plot_shannons[[2]] <- early_plot_shannons[[2]]+theme(legend.position = "none")
unstim_plot_freq_m <- grid.arrange(unstim_plot_freqs[[1]], unstim_plot_freqs[[2]], unstim_plot_freqs[[3]], nrow = 1)
unstim_3_plot_freqs_m <- grid.arrange(unstim_3_plot_freqs[[1]], unstim_3_plot_freqs[[2]], unstim_3_plot_freqs[[3]], nrow = 1)
early_plot_top <- plot_grid(early_plot_freqs[[1]], early_plot_n_clones[[1]], early_plot_avg_freqs[[1]], early_plot_shannons[[1]], nrow = 1, rel_widths = c(1,1,1,1), align = "h")
early_plot_bot <- plot_grid( early_plot_freqs[[2]], early_plot_n_clones[[2]], early_plot_avg_freqs[[2]], early_plot_shannons[[2]], nrow = 1, rel_widths = c(1,1,1,1), align = "h")
early_plot_w0_leg <- plot_grid(early_plot_top, early_plot_bot, nrow = 2)
early_plot <- plot_grid(early_plot_w0_leg, legend_for_plot, nrow = 1, rel_widths = c(1, .1))
plot(early_plot)
#
ggsave(paste0(OUTPUT_PATH, '/Figure3/PTCyD3VEarliestTP.png'), early_plot,  height = 8, width=16, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/PTCyD3VEarliestTP.pdf'), early_plot, height = 8, width = 16, dpi = 600)


```
```{r}
for(rep_div in c("allo")){#}, "nonallo", "all")){
  if (rep_div == "allo"){
    i = 1
    rep_title = "Alloreactive"
  }else if(rep_div == "nonallo"){
    i = 2
    rep_title = "Non-Alloreactive"
  }else{
    i = 3
    rep_title = "All"
  }
  patient_data_allo <- dplyr::full_join(patient_data_all, meta_data,  by = "PatientID")%>%
    mutate(timepoint = SampleID)%>%
    select(-c(SampleID))
  colnames(patient_data_allo) <- sapply(colnames(patient_data_allo), function(x){str_replace_all(x, "-", "")})
  patient_data_allo <- patient_data_allo[patient_data_allo$Rep_div == rep_div,]
  patient_data_allo <- patient_data_allo[which(!is.na(patient_data_allo$timepoint)),]
  patient_data_allo[patient_data_allo$timepoint == "MLRCFSElo",]$timepoint  <- "1"
  patient_data_allo[patient_data_allo$timepoint == "unstimulated",]$timepoint  <- "0"
  patient_data_allo_copy <- patient_data_allo%>%
    mutate(timepoint = strtoi(timepoint))
  patient_data_allo_copy <- patient_data_allo_copy[which(!is.na(patient_data_allo_copy$timepoint)),]


  patient_data_allo_copy <- patient_data_allo_copy%>%
    mutate(GVHD_GRADE_1 = ifelse(grepl("Severe", GVHD_GRADE_1), "Severe", GVHD_GRADE_1))%>%
    mutate(GVHD_GRADE_1 = factor(GVHD_GRADE_1, levels = c("No", "Mild", "Severe")))%>%
    replace_na(list(shannons.diversity = 0, shannons.entropy = 0))#%>%
    # mutate(PTCy = ifelse(grepl("PTCy", PTCy), "PTCy", "No PTCy"))

  df_unstimulated <- patient_data_allo_copy[patient_data_allo_copy$timepoint == 0,]%>%
    mutate(timepoint = "Donor")%>%
    filter(PTCy == "PTCy")

  df_unstimulated_all <- patient_data_allo_copy[patient_data_allo_copy$timepoint == 0,]%>%
    mutate(timepoint = "Donor")


  patient_data_allo_copy <- patient_data_allo_copy[patient_data_allo_copy$timepoint >= 2,]
  # patient_data_allo <- patient_data_allo[!is.na(patient_data_allo$ID),]

  df_early_timepoint_all <- get_early_timepoint(patient_data_allo_copy)%>%
    mutate(timepoint = ifelse(timepoint <= 3, "<= 3", "Earliest Timepoint"))%>%
    mutate(timepoint = factor(timepoint, levels = c("<= 3", "Earliest Timepoint")))%>%
    group_by(PatientID,GVHD_GRADE_1, timepoint)

  df_early_timepoint <- df_early_timepoint_all %>%
    filter(PTCy == "PTCy")

  df_early_timepoint <- df_early_timepoint[df_early_timepoint$PatientID != "R070",]

  data_CD48_all_expand_adj <- dplyr::full_join(data_CD48_all_expand, clinical_data, by = 'PatientID')
  data_CD48_all_expand_adj <- data_CD48_all_expand_adj[!is.na(data_CD48_all_expand_adj$cdr3_amino_acid),]
  data_CD48_all_expand_adj <- data_CD48_all_expand_adj[data_CD48_all_expand_adj$PatientID != "R070",]

  df_timepoint <- get_timepoint(patient_data_allo_copy)%>%
    mutate(timepoint = ifelse(timepoint <= 3 & timepoint >=2, "<= 3", "Earliest Timepoint"))%>%
    # mutate(GVHD_GRADE_1 = ifelse(grepl("Severe",GVHD_GRADE_1), "Severe", GVHD_GRADE_1), GVHD_GRADE_2 = ifelse(grepl("Severe",GVHD_GRADE_2), "Severe", GVHD_GRADE_2))%>%
    mutate(timepoint = factor(timepoint, levels = c("Donor", "<= 3", "Earliest Timepoint")))%>%
    filter(PTCy == "PTCy")#%>%
    # group_by(PatientID,GVHD_GRADE_1, timepoint)
  df_timepoint <- df_timepoint[df_timepoint$PatientID != 70,]


  df_unstimulated_3 <- bind_rows(df_unstimulated%>%filter(PatientID %in% unique(df_timepoint$PatientID)), df_early_timepoint)%>%
    mutate(timepoint = factor(timepoint, levels = c("Donor", "<= 3", "Earliest Timepoint")))%>%
    filter(GVHD_GRADE_1 != "No")%>%
    group_by(PatientID)%>%
    mutate(n_in = n())%>%
    filter(n_in >= 3)%>%
    ungroup()%>%
    replace_na(list(avg_freq = 0))

  df_unstimulated_filt <- df_unstimulated_3%>%filter(timepoint != "Donor")%>%
    select(PatientID, GVHD_GRADE_1, shannons.diversity, timepoint)
  # View(df_unstimulated_filt)  # interactive only

  results <- t.test(as.formula("shannons.diversity ~ timepoint"), data = df_unstimulated_filt, exact = F, paired = T)
  print(results)
}
```
```{r}
all_data_squished <- bind_rows(lapply(data, bind_rows))
all_pat <- all_data_squished%>%
    filter(timepoint == "3" | timepoint == "2")
patients <- unique(all_pat$PatientID)
pat_idx <- which(unique(data_squished$PatientID) %in% patients)
data_allo3 <- vector("list", length(patients))
for(i in seq(1,length(pat_idx),1)){
  immdata2 <- data[[pat_idx[i]]]
  immdata2_squished <- bind_rows(data[[pat_idx[i]]])

  # allo_cd48 <- all_pat%>%
  #   filter(PatientID == patients[i])%>%
  #   subset(select = c(unique_identifiers, "cell_type", "allo"))
  immdata_3 <- immdata2_squished%>%
    filter(timepoint == "3" | timepoint == "2")

  immdata_unstim <- immdata2_squished%>%
    filter(timepoint == "unstimulated")

  data_3_allo <- full_join(immdata_unstim, immdata_3, by = c(unique_identifiers, "PatientID"),
                           suffix = c(".unstim", ".3"))%>%
    replace_na(list(templates.unstim = 0, templates.3 = 0, frequency.unstim = 0, templates.3 = 0))%>%
    filter(frequency.3 >= 2*frequency.unstim & frequency.3 >= 1e-5)%>%
    mutate(cell_type = cell_type.unstim)%>%
    replace_na(list(cell_type = "CD4CD8"))%>%
    select(-c("cell_type.unstim", "cell_type.3"))

  data_3_allo_clone <- data_3_allo %>%
    select(c(unique_identifiers))
  data_3 <- lapply(immdata2, function(x) {
      x%>%
      dplyr::right_join(data_3_allo_clone, by =  c(unique_identifiers))%>%
      replace_na(list(frequency = 0, templates = 0))#%>%
      #mutate(cell_type = cell_type.y, timepoint = na.omit(timepoint)[1], PatientID = na.omit(PatientID)[1], tag = paste(cdr3_amino_acid, v_resolved, j_resolved))%>%
      #select(-c(cell_type.x, cell_type.y))

    }
  )

  data_allo3[[i]] <- data_3

}

```

```{r}
res_allo <- data_allo_squished_w0 %>%
  group_by(PatientID, timepoint,cell_type)%>%
  summarise(cum_freq = sum(frequency))%>%
  filter(cell_type != "CD4CD8")

res_nonallo <- data_nonallo_squished_w0 %>%
  group_by(PatientID, timepoint, cell_type)%>%
  summarise(cum_freq = sum(frequency))%>%
  filter(cell_type != "CD4CD8")
```

```{r, fig.height = 3.2, fig.width=5, dpi = 600}
nonallo_all_CD4 <- bind_rows(lapply(all_nonallo_div_CD4, bind_rows))%>%
  filter(!is.na(shannons.diversity))%>%
  mutate(ids = str_split(ID, "_"), rep_div = "nonallo_CD4")%>%
  mutate(PatientID = sapply(ids, function(x){x[[1]]}), timepoint = sapply(ids, function(x){x[[2]]}))%>%
  full_join(res_nonallo[res_nonallo$cell_type == "CD4",], by = c("PatientID", "timepoint"))

nonallo_all_CD8 <- bind_rows(lapply(all_nonallo_div_CD8, bind_rows))%>%
  filter(!is.na(shannons.diversity))%>%
  mutate(ids = str_split(ID, "_"), rep_div = "nonallo_CD8")%>%
  mutate(PatientID = sapply(ids, function(x){x[[1]]}), timepoint = sapply(ids, function(x){x[[2]]}))%>%
  full_join(res_nonallo[res_nonallo$cell_type == "CD8",], by = c("PatientID", "timepoint"))

allo_all_CD4 <- bind_rows(lapply(all_allo_div_CD4, bind_rows))%>%
  filter(!is.na(shannons.diversity))%>%
  mutate(ids = str_split(ID, "_"), rep_div = "allo_CD4")%>%
  mutate(PatientID = sapply(ids, function(x){x[[1]]}), timepoint = sapply(ids, function(x){x[[2]]}))%>%
  full_join(res_allo[res_allo$cell_type == "CD4",], by = c("PatientID", "timepoint"))

allo_all_CD8 <- bind_rows(lapply(all_allo_div_CD8, bind_rows))%>%
  filter(!is.na(shannons.diversity))%>%
  mutate(ids = str_split(ID, "_"), rep_div = "allo_CD8")%>%
  mutate(PatientID = sapply(ids, function(x){x[[1]]}), timepoint = sapply(ids, function(x){x[[2]]}))%>%
  full_join(res_allo[res_allo$cell_type == "CD8",], by = c("PatientID", "timepoint"))

all_CD48_div <- bind_rows(nonallo_all_CD4, nonallo_all_CD8, allo_all_CD4, allo_all_CD8)%>%
  full_join(meta_data_clin, by = c("PatientID"))%>%
  filter(!is.na(ID))

all_CD48_div[all_CD48_div$timepoint == "MLRCFSElo",]$timepoint  <- "1"
all_CD48_div[all_CD48_div$timepoint == "unstimulated",]$timepoint  <- "0"
all_CD48_div <- all_CD48_div%>%
    mutate(timepoint = strtoi(timepoint), GVHD_GRADE_1 = ifelse(grepl("Severe", GVHD_GRADE_1), "Severe", GVHD_GRADE_1))

for(r_div in c("allo_CD4", "allo_CD8", "nonallo_CD4", "nonallo_CD8")){
  if (r_div == "allo_CD4"){
    rep_title = "CD4+ Alloreactive"
  }else if (r_div == "allo_CD8"){
    rep_title = "CD8+ Alloreactive"
  }else if (r_div == "nonallo_CD4"){
    rep_title = "CD4+ Non-Alloreactive"
  } else{
    rep_title = "CD8+ Non-Alloreactive"
  }

  rep_div_CD48_div <- all_CD48_div%>%
    filter(rep_div == r_div)

  df_unstimulated <- rep_div_CD48_div[rep_div_CD48_div$timepoint == 0,]%>%
    mutate(timepoint = "unstimulated")%>%
    filter(PTCy == "PTCy")

  df_unstimulated_all <- rep_div_CD48_div[rep_div_CD48_div$timepoint == 0,]%>%
    mutate(timepoint = "unstimulated")%>%
    filter(!is.na(ID))


  patient_data_allo_copy <- rep_div_CD48_div[rep_div_CD48_div$timepoint >= 2,]
  # patient_data_allo <- patient_data_allo[!is.na(patient_data_allo$ID),]

  df_early_timepoint_all <- get_early_timepoint(patient_data_allo_copy)%>%
    mutate(timepoint = ifelse(timepoint <= 3, "<= 3", "Earliest Timepoint"))%>%
    mutate(timepoint = factor(timepoint, levels = c("<= 3", "Earliest Timepoint")), GVHD_GRADE_1 = factor(GVHD_GRADE_1, levels = c("No", "Mild", "Severe")))%>%
    group_by(PatientID,GVHD_GRADE_1, timepoint)

  df_early_timepoint <- df_early_timepoint_all %>%
    filter(PTCy == "PTCy")

  df_early_timepoint <- df_early_timepoint[df_early_timepoint$PatientID != "R070",]


  df_timepoint <- get_timepoint(patient_data_allo_copy)%>%
    mutate(timepoint = ifelse(timepoint <= 3 & timepoint >=2, "<= 3", "Earliest Timepoint"))%>%
    mutate(GVHD_GRADE_1 = ifelse(grepl("Severe",GVHD_GRADE_1), "Severe", GVHD_GRADE_1), GVHD_GRADE_2 = ifelse(grepl("Severe",GVHD_GRADE_2), "Severe", GVHD_GRADE_2))%>%
    mutate(timepoint = factor(timepoint, levels = c("<= 3", "Earliest Timepoint")), GVHD_GRADE_1 = factor(GVHD_GRADE_1, levels = c("No", "Mild", "Severe")))%>%
    filter(PTCy == "PTCy")%>%
    group_by(PatientID,GVHD_GRADE_1, timepoint)
  df_timepoint <- df_timepoint[df_timepoint$PatientID != 70,]


  df_unstimulated_3 <- bind_rows(df_unstimulated%>%filter(PatientID %in% unique(df_timepoint$PatientID)), df_early_timepoint[df_early_timepoint$timepoint == "<= 3",])%>%
    mutate(timepoint = factor(timepoint, levels = c("unstimulated", "<= 3")))


   unstim_plot_freq <- ggplot(df_unstimulated_all, aes(x = PTCy, y = cum_freq, fill = PTCy))+
    geom_boxplot()+
    geom_beeswarm(aes(color = GVHD_GRADE_1))+
    scale_color_manual(values = c("#09BB8C", "#005A8F", "#B85000", "grey"))+
    stat_compare_means(comparisons = list(c("PTCy", "No PTCy")), method = "wilcox.test", label = "p.format", hide.ns = FALSE, label.y = max(df_unstimulated_all$cum_freq)-.01)+
    labs(y = "Frequency", title = paste(rep_title, "Unstimulated"), color = "GVHD Grade")+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"))+
    expand_limits(y = max(df_unstimulated_all$cum_freq)+.05)+
    theme_minimal()+
    theme(plot.title = element_text(size = 18), axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14), axis.text = element_text(size = 12))


  unstim_3_plot_freq <- ggplot(df_unstimulated_3, aes(x = timepoint, y = cum_freq, shape = PatientID))+
    geom_point(aes(color = GVHD_GRADE_1), size = 2)+
    geom_line(aes(group = PatientID, color = GVHD_GRADE_1), linewidth = 1.5)+
    scale_color_manual(values = c( "#005A8F", "#B85000", "grey"))+
    stat_compare_means(comparisons = list(c("unstimulated", "<= 3")), method = "wilcox.test", paired = TRUE, label = "p.format", hide.ns = FALSE, group.by = "PatientID", label.y = max(df_unstimulated_3$cum_freq)-.01)+
    labs(x = "Timepoint", y = "Frequency", title = paste(rep_title, "Unstimulated"), color = "GVHD Grade")+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"))+
    expand_limits(y = max(df_unstimulated_3$cum_freq)+.05)+
    theme_minimal()+
    theme(plot.title = element_text(size = 18), axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14), axis.text = element_text(size = 12))

  earliest_plot_freq <- ggplot(df_early_timepoint_all[df_early_timepoint_all$timepoint == "Earliest Timepoint",], aes(x = PTCy, y = cum_freq, fill = PTCy))+
    geom_boxplot()+
    geom_beeswarm(aes(color = GVHD_GRADE_1))+
    scale_color_manual(values = c("#09BB8C", "#005A8F", "#B85000", "grey"))+
    stat_compare_means(comparisons = list(c("PTCy", "No PTCy")), method = "wilcox.test",label = "p.format", hide.ns = FALSE, label.y = max(df_early_timepoint_all$cum_freq)-.01)+
    labs(y = "Frequency", title = paste(rep_title, "Earliest Timepoint"), color = "GVHD Grade")+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"))+
    expand_limits(y = max(df_early_timepoint_all$cum_freq)+.05)+
    theme_minimal()+
    theme(plot.title = element_text(size = 18), axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14), axis.text = element_text(size = 12))

  early_plot_freq <- ggplot(df_timepoint, aes(x = timepoint, y = cum_freq, shape = PatientID))+
    geom_line(aes(group = PatientID, color = GVHD_GRADE_1), linewidth = 1.5)+
    geom_point(aes(color = GVHD_GRADE_1), size = 2)+
    stat_compare_means(comparisons = list(c("<= 3", "Earliest Timepoint")), method = "wilcox.test", paired = TRUE, label = "p.format", hide.ns = FALSE, group.by = "PatientID", label.y = max(df_timepoint$cum_freq)-.01)+
    scale_color_manual(values = c("#005A8F", "#B85000", "grey"))+
    expand_limits(y = max(df_timepoint$cum_freq)+.05)+
    labs(x = "Timepoint", y = "Frequency", title = rep_title, color = "GVHD Grade")+
    theme_minimal()+
    theme(plot.title = element_text(size = 18), axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14), axis.text = element_text(size = 12))


  unstim_plot_shannon <- ggplot(df_unstimulated_all, aes(x = PTCy, y = shannons.diversity, fill = PTCy))+
    geom_boxplot()+
    geom_beeswarm(aes(color = GVHD_GRADE_1))+
    scale_color_manual(values = c("#09BB8C", "#005A8F", "#B85000", "grey"))+
    stat_compare_means(comparisons = list(c("PTCy", "No PTCy")), method = "wilcox.test",label = "p.format", hide.ns = FALSE, label.y = max(df_unstimulated_all$shannons.diversity)+2)+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"))+
    expand_limits(y = max(df_unstimulated_all$shannons.diversity)+3)+
    labs(y = "Shannon's Diversity", title = paste(rep_title, "Unstimulated"), color = "GVHD Grade")+
    theme_minimal()+
    theme(plot.title = element_text(size = 18), axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14), axis.text = element_text(size = 12))

  unstim_3_plot_shannon <- ggplot(df_unstimulated_3, aes(x = timepoint, y = shannons.diversity, shape = PatientID))+
    geom_beeswarm(aes(color = GVHD_GRADE_1), size = 2)+
    geom_line(aes(group = PatientID, color = GVHD_GRADE_1), linewidth = 1.5)+
    scale_color_manual(values = c("#005A8F", "#B85000", "grey"))+
    stat_compare_means(comparisons = list(c("unstimulated", "<= 3")), method = "wilcox.test", paired = TRUE, label = "p.format", hide.ns = FALSE, group.by = "PatientID", label.y = max(df_unstimulated_3$shannons.diversity)+2)+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"))+
    expand_limits(y = max(df_unstimulated_3$shannons.diversity)+3)+
    labs(x = "Timepoint", y = "Shannon's Diversity", title = paste(rep_title, "Unstimulated"), color = "GVHD Grade")+
    theme_minimal()+
    theme(plot.title = element_text(size = 18), axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14), axis.text = element_text(size = 12))

  earliest_plot_shannon <- ggplot(df_early_timepoint_all[df_early_timepoint_all$timepoint == "Earliest Timepoint",], aes(x = PTCy, y = shannons.diversity, fill = PTCy))+
    geom_boxplot()+
    geom_beeswarm(aes(color = GVHD_GRADE_1))+
    scale_color_manual(values = c("#09BB8C", "#005A8F", "#B85000", "grey"))+
    stat_compare_means(comparisons = list(c("PTCy", "No PTCy")), method = "wilcox.test",label = "p.format", hide.ns = FALSE, label.y = max(df_early_timepoint_all$shannons.diversity)+2)+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"))+
    expand_limits(y = max(df_early_timepoint_all$shannons.diversity)+3)+
    labs(y = "Shannon's Diversity", title = paste(rep_title, "Earliest Timepoint"), color = "GVHD Grade")+
    theme_minimal()+
    theme(plot.title = element_text(size = 18), axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14), axis.text = element_text(size = 12))

  # df_early_timepoint <- df_early_timepoint%>%
  #   filter(PatientID %in% unique(df_timepoint$PatientID))
  df_timepoint_ptcy <- df_timepoint%>%filter(PatientID %in% unique(df_timepoint$PatientID))

  early_plot_shannon <- ggplot(df_timepoint_ptcy, aes(x = timepoint, y = shannons.diversity, shape = PatientID))+
    geom_line(aes(group = PatientID, color = GVHD_GRADE_1), linewidth = 1.5)+
    geom_beeswarm(aes(color = GVHD_GRADE_1), size = 2)+
    stat_compare_means(comparisons = list(c("<= 3", "Earliest Timepoint")), method = "wilcox.test", paired = TRUE, label = "p.format", hide.ns = FALSE, group.by = "PatientID", label.y = max(df_timepoint_ptcy$shannons.diversity)+2)+
    scale_color_manual(values = c( "#005A8F", "#B85000", "grey"))+
    labs(x = "Timepoint", y = "Shannon's Diversity", title = rep_title, color = "GVHD Grade")+
    expand_limits(y = max(df_timepoint_ptcy$shannons.diversity)+3)+
    theme_minimal()+
    theme( plot.title = element_text(size = 18, margin = margin(b = 20, unit = "pt")), axis.title.x = element_text(size = 14), axis.title.y = element_text(size = 14), axis.text = element_text(size = 12))

  plot(unstim_plot_freq)
  plot(unstim_3_plot_freq)
  plot(early_plot_freq)
  plot(earliest_plot_freq)
  plot(unstim_plot_shannon)
  plot(unstim_3_plot_shannon)
  plot(early_plot_shannon)
  plot(earliest_plot_shannon)

ggsave(paste0(OUTPUT_PATH, '/',r_div,"unstim_plot_freq.png"), unstim_plot_freq, width = 5, height = 3.2, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/',r_div,"unstim_3_plot_freq.png"), unstim_3_plot_freq, width = 5, height = 3.2, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/',r_div,"early_plot_freq.png"), early_plot_freq, width = 5, height = 3.2, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/',r_div,"earliest_plot_freq.png"), earliest_plot_freq, width = 5, height = 3.2, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/',r_div,"unstim_plot_shannon.png"), unstim_plot_shannon, width = 5, height = 3.2, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/',r_div,"unstim_3_plot_shannon.png"), unstim_3_plot_shannon, width = 5, height = 3.2, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/',r_div,"early_plot_shannon.png"), early_plot_shannon, width = 5, height = 3.2, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/',r_div,"earliest_plot_shannon.png"), earliest_plot_shannon, width = 5, height = 3.2, dpi = 600)
}
```



```{r}
clone_fig <- function(immdata, type, title, alpha = 0.3) {
  #' Visualize clone frequencies over time
  #'
  #' @description This function visualizes the frequency of clones over time for different groups using scatter and line plots.
  #'
  #' @param immdata A dataframe containing immunosequencing data with `timepoint`, `frequency`, `tag`, and specified `type`.
  #' @param type A character string specifying the grouping variable for the analysis.
  #' @param title A character string for the plot title.
  #' @param alpha A numeric value indicating the transparency level of points and lines in the plot (default is 0.3).
  #' @usage clone_fig(immdata, type, title, alpha)
  #' @return A ggplot object showing the clone frequency over time.

  # Convert timepoints to integer and remove NA values
  immdata <- immdata %>%
    mutate(timepoint = strtoi(timepoint)) %>%
    filter(!is.na(timepoint))

  # Calculate average and standard deviation of frequency per group and timepoint
  immdata_stat <- immdata %>%
    group_by(across(all_of(c(type, "timepoint")))) %>%
    summarise(
      avg_freq = mean(frequency, na.rm = TRUE),
      std_freq = sd(frequency, na.rm = TRUE),
      .groups = 'drop'
    )

  # Generate the plot
  fig <- ggplot(immdata, aes(x = timepoint, y = frequency, color = .data[[type]], group = tag)) +
    geom_point(size = 1, alpha = alpha) +
    geom_line(alpha = alpha) +
    labs(title = title, x = "Timepoint", y = "Frequency") +
    scale_y_continuous(trans = "log10", labels = scales::number_format(accuracy = 0.00001)) +
    scale_colour_discrete(na.translate = FALSE) +
    scale_shape_discrete(na.translate = FALSE) +
    guides(color = guide_legend(override.aes = list(alpha = 1))) +
    theme_pubr() +
    theme(
      axis.text.x = element_text(angle = 60, vjust = 0.5),
      legend.text = element_markdown(size = 20)
    )

  return(fig)
}

```


```{r, warning=FALSE, fig.width=8, fig.height = 4}


data_CD48_all_expand_adj <- data_CD48_all_expand
data_CD48_all_expand_adj$cell_type <- gsub(" ", "",data_CD48_all_expand_adj$cell_type )
data_CD48_all_expand_adj <- dplyr::full_join(data_CD48_all_expand_adj, clinical_data, by = "PatientID")%>%
  mutate(GVHD_GRADE_1 = ifelse(grepl("Severe", GVHD_GRADE_1), "Severe", GVHD_GRADE_1))%>%
  mutate(GVHD_GRADE_1 = factor(GVHD_GRADE_1, levels = c("No", "Mild", "Severe")))


All_by_grade <- clone_fig(data_CD48_all_expand_adj, 'GVHD_GRADE_1', "", alpha = 0.1)
All_by_grade_fig_ex <- All_by_grade + theme(text = element_text(size = 20))+
  scale_color_manual(values = c("#09BB8C", "#005A8F", "#B85000", "grey"), labels = c(
      No = "<span style='color:#09BB8C;'>No</span>",
      Mild = "<span style='color:#005A8F;'>Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))+
  coord_cartesian(xlim = c(0,365))+
  labs(y = "Expanded Alloreactive\n
       Clone Frequency", x = "Days", color = "GVHD Grade")+
  theme(axis.title.y = element_text(lineheight = 0.5))


All_by_ptcy <- clone_fig(data_CD48_all_expand_adj, 'PTCy', "Expanded Alloreactive Clones", alpha = 0.3)
All_by_ptcy_fig_ex <- All_by_ptcy +
  theme(text = element_text(size = 20)) +
  scale_color_manual(values = c("#E6BE60", "#A483AF"),
                    labels = c(
                      `No PTCy` = "<span style='color:#E6BE60;'>No PTCy</span>",
                      PTCy = "<span style='color:#A483AF;'>PTCy</span>")) +
  coord_cartesian(xlim = c(0,365)) +
  labs(y = "Expanded Alloreactive\n
       Clone Frequency", x = "Days", color = "PTCy")+
  theme(axis.title.y = element_text(lineheight = 0.5))


plot(All_by_grade_fig_ex)
plot(All_by_ptcy_fig_ex)

ggsave(paste0(OUTPUT_PATH, '/Figure1/All_by_grade_fig.png'), All_by_grade_fig_ex, width = 8, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/All_by_ptcy_fig.png'), All_by_ptcy_fig_ex, width = 8, height = 5, dpi = 600)


ggsave(paste0(OUTPUT_PATH, '/Figure1/All_by_grade_fig.pdf'), All_by_grade_fig_ex, width = 8, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/All_by_ptcy_fig.pdf'), All_by_ptcy_fig_ex, width = 8, height = 5, dpi = 600)

```

```{r}

avg_clone_fig <- function(immdata, type, title = "", num_cuts = 5, groupings = NA, colors = c("#E6BE60", "#A483AF"), method = "hochberg", legend_title = "", ylab = "") {
  #' Visualize average clone frequency over time
  #'
  #' @description This function processes immunosequencing data to compute average clone frequencies over time, divides them into bins, performs statistical tests, and visualizes the results.
  #'
  #' @param immdata A dataframe containing immunosequencing data with `timepoint`, `PatientID`, and specified `type`.
  #' @param type A character string specifying the grouping variable for the analysis.
  #' @param title A character string for the plot title.
  #' @param num_cuts An integer indicating the number of bins to divide the timepoints into (default is 5).
  #' @param groupings Optional grouping variable for further subsetting (default is NA).
  #' @param colors A character vector specifying colors for the plot (default is c("#E6BE60", "#A483AF")).
  #' @param method A character string specifying the p-value adjustment method (default is "hochberg").
  #' @param legend_title A character string for the legend title.
  #' @param ylab A character string for the y-axis label in the plot.
  #' @usage avg_clone_fig(immdata, type, title, num_cuts, groupings, colors, method, legend_title, ylab)
  #' @return A list containing the plot, statistical test results, processed data, and summary statistics.

  # Convert timepoints to integer and filter data
  immdata <- immdata %>%
    mutate(timepoint = strtoi(timepoint)) %>%
    filter(!is.na(timepoint), timepoint <= 365)

  # Separate early timepoints (<=3 days) and remaining timepoints
  immdata_3 <- immdata %>%
    filter(timepoint <= 3, templates != 0) %>%
    mutate(timepoint = 3, bins = "3")

  immdata <- immdata %>%
    filter(timepoint > 3, templates != 0)

  # Create bins for timepoints
  breaks <- unique(quantile(immdata$timepoint, probs = 0:num_cuts/num_cuts, na.rm = TRUE))
  immdata <- immdata %>%
    mutate(bins = cut(timepoint, breaks = breaks, include.lowest = TRUE))

  # Create an all-timepoint reference dataset
  immdata_all_timepoint <- immdata %>%
    select(all_of(c("timepoint", "PatientID", type))) %>%
    distinct() %>%
    mutate(bins = cut(timepoint, breaks = breaks, include.lowest = TRUE))

  # Combine early and binned timepoints, setting factor levels
  if (nrow(immdata_3) > 0) {
    immdata <- bind_rows(immdata_3, immdata) %>%
      mutate(bins = factor(bins, levels = c("3", levels(immdata_all_timepoint$bins))))
  } else {
    immdata <- immdata %>%
      mutate(bins = factor(bins, levels = levels(immdata_all_timepoint$bins)))
  }

  # Aggregate data for plotting
  immdata_fig <- immdata %>%
    group_by(across(all_of(c("bins", "timepoint", "PatientID", type)))) %>%
    full_join(immdata_all_timepoint, by = c("PatientID", "bins", "timepoint", type)) %>%
    replace_na(list(frequency = 0)) %>%
    group_by(across(all_of(c("bins", "PatientID", type)))) %>%
    summarise(frequency = mean(frequency), .groups = 'drop')

  # Summarize data for error bars
  immdata_sum <- immdata_fig %>%
    group_by(across(all_of(c("bins", type)))) %>%
    summarise(m = mean(frequency), s = sd(frequency), .groups = 'drop')

  # Perform pairwise Wilcoxon tests
  stat_test <- immdata_fig %>%
    group_by(bins) %>%
    filter(n() >= 3) %>%
    pairwise_wilcox_test(as.formula(paste0("frequency ~ ", type)), p.adjust.method = method, exact = FALSE) %>%
    add_xy_position(x = "bins") %>%
    mutate(
      y.position = log10(y.position),
      p.adj = p.adjust(p, method = method),
      p.adj.signif = symnum(
        p.adj,
        cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1),
        symbols = c("****", "***", "**", "*", "ns")
      )
    )

  # Generate the plot
  fig <- ggplot(immdata_sum, aes(x = bins, y = m, fill = .data[[type]], group = .data[[type]], color = .data[[type]])) +
    geom_line() +
    geom_point() +
    geom_ribbon(aes(ymin = pmax(0, m - s), ymax = m + s, linetype = NA), alpha = 0.3) +
    geom_errorbar(aes(ymin = pmax(0, m - s), ymax = m + s), width = 0.1) +
    scale_x_discrete(na.translate = FALSE) +
    theme_minimal() +
    theme(
      text = element_text(size = 16),
      axis.text.x = element_text(angle = 75, vjust = 0.5, size = 12),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(color = "black"),
      axis.ticks = element_line(color = "black"),
      axis.ticks.length = unit(0.25, "cm")
    ) +
    labs(title = title, y = ylab, x = "Days") +
    scale_fill_manual(values = colors) +
    scale_color_manual(values = colors)

  return(list(fig, stat_test, immdata_fig, immdata_sum)) # Return plot, statistical tests, and processed data
}


```


```{r, warning=FALSE, fig.width=8, fig.height = 5}


data_CD48_all_expand_adj <- data_CD48_all_expand
data_CD48_all_expand_adj$cell_type <- gsub(" ", "",data_CD48_all_expand_adj$cell_type )
data_CD48_all_expand_adj <- dplyr::full_join(data_CD48_all_expand_adj, clinical_data, by = "PatientID")%>%
  mutate(GVHD_GRADE_1 = ifelse(grepl("Severe", GVHD_GRADE_1), "Severe", GVHD_GRADE_1))%>%
  mutate(GVHD_GRADE_1 = factor(GVHD_GRADE_1, levels = c("No", "Mild", "Severe")))
# data_CD48_all_expand_adj <- data_CD48_all_expand_adj[data_CD48_all_expand_adj$GVHD_GRADE_1 != "Unclassified/Severe",]

All_by_grade <- avg_clone_fig(data_CD48_all_expand_adj, "GVHD_GRADE_1", title = "", num_cuts = 7, groupings = NA, colors = c("#09BB8C", "#005A8F", "#B85000", "grey"), method = "hochberg", legend_title = "", ylab = "")#clone_fig(data_CD48_all_expand_adj, 'GVHD_GRADE_1', "Expanded Alloreactive Clones", alpha = 0.1)
All_by_grade_fig <- All_by_grade[[1]] + theme(text = element_text(size = 20))+
  scale_color_manual(values = c("#09BB8C", "#005A8F", "#B85000", "grey"))+
  scale_fill_manual(values = c("#09BB8C", "#005A8F", "#B85000", "grey"))+
  labs(y = "Frequency", x = "Days", color = "GVHD Grade")

All_by_ptcy <- avg_clone_fig(data_CD48_all_expand_adj, "PTCy", title = "", num_cuts = 7, groupings = NA, colors = c("#E6BE60", "#A483AF"), method = "hochberg", legend_title = "", ylab = "")#clone_fig(data_CD48_all_expand_adj, 'PTCy', "Expanded Alloreactive Clones", alpha = 0.5)
All_by_ptcy_fig <- All_by_ptcy[[1]] + theme(text = element_text(size = 20))+
  scale_color_manual(values = c("#E6BE60", "#A483AF"))+
  labs(y = "Frequency", x= "Days", color = "PTCy")


plot(All_by_grade_fig)
plot(All_by_ptcy_fig)

```

```{r}
count_clones <- function(data, type, metric = "cum_freq", num_cuts = 5, group_by = c("PatientID","timepoint", "PTCy")){
  #'
  #' @description Bins the clones over time.
  #'
  #' @param data List of dataframes containing the data from immunoseq files.
  #' Dataframes are obtained through the function read_immunoseq
  #' @param type Grouping you would like to use
  #' @param metric diverseity metric you would like to use
  #' @param num_cuts, the number of bins you would like
  #'
  #'
  #' @usage count_clones(data, type, metric = "cum_freq", num_cuts = 5)
  #' @return updated: list(data_pre, data_post)
  #'
  #'
  data_proc <- data%>%
    group_by(across(all_of(c(group_by, type))))%>%
    dplyr::summarise(num_clones = sum(frequency), .groups = "keep")

  data_pre <- data_proc[grepl("MLR|unstim", data_proc$timepoint),] #Seperate timepoints before transplant

  data_proc <- data_proc %>%
    mutate(timepoint = strtoi(timepoint))
  data_proc <- data_proc[!is.na(data_proc$timepoint),]


  data_post <- data_proc[data_proc$timepoint <= 365 & data_proc$timepoint > 3,] %>%
    subset(!is.na(timepoint))%>%
    ungroup()

  qs <- matrix(nrow = length(unique(data_post[[type]])), ncol = num_cuts+1)
  for(i in seq_along(unique(data_post[[type]]))){
    t <- unique(data_post[[type]])[[i]]
    qs[i,] <- quantile(data_post[data_post[[type]] == t,]$timepoint, probs = 0:num_cuts/num_cuts)
  }

  qs_breaks <- apply(qs,2, max)

  breaks <- unique(quantile(data_post$timepoint, probs = 0:num_cuts/num_cuts))

  data_post <- data_post%>%
    mutate(bins = cut(timepoint,breaks = breaks, include.lowest = TRUE))

  return(list(data_pre, data_post))
}

num_clones <- function(data, type, metric = "cum_freq", num_cuts = 5, title, ylab = "Allo Frequency", text_size = 20, group_by = c("PatientID", "timepoint", "PTCy")) {
  #' Analyze number of clones and visualize results
  #'
  #' @description This function calculates the number of clones based on specific metrics, performs statistical comparisons between groups, and visualizes the results using boxplots with significance annotations.
  #'
  #' @param data A dataframe containing clone data, including a `SampleID` column.
  #' @param type A character string specifying the grouping variable for the analysis.
  #' @param metric A character string specifying the metric to use for clone frequency calculation (default is "cum_freq").
  #' @param num_cuts An integer indicating the number of bins to divide the timepoints into (default is 5).
  #' @param title A character string for the plot title.
  #' @param ylab A character string for the y-axis label in the plot (default is "Allo Frequency").
  #' @param text_size An integer specifying the size of text in the plot (default is 20).
  #' @param group_by A character vector specifying the grouping variables for clone counting (default is c("PatientID", "timepoint", "PTCy")).
  #' @usage num_clones(data, type, metric, num_cuts, title, ylab, text_size, group_by)
  #' @return A list containing the boxplot with significance annotations, the Wilcoxon test results, and the processed data.

  results <- count_clones(data, type, metric, num_cuts, group_by = group_by)
  data_post <- results[[2]]
  data_post$type_num <- as.numeric(factor(data_post[[type]]))

  # Filter data_post for non-zero clone numbers
  data_post_n0 <- data_post %>%
    filter(num_clones != 0)

  # Perform Wilcoxon tests and adjust p-values
  wilcox_results <- compare_means(as.formula(paste0("num_clones ~ ", type)), data = data_post, group.by = "bins")

  stat_test <- data_post %>%
    group_by(bins) %>%
    pairwise_wilcox_test(as.formula(paste0("num_clones ~ ", type)), p.adjust.method = "hochberg") %>%
    add_xy_position(x = "bins") %>%
    mutate(
      p.adj = p.adjust(p, method = "hochberg"),
      p.adj.signif = symnum(
        p.adj,
        cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1),
        symbols = c("****", "***", "**", "*", "ns")
      )
    )

  print(colnames(data_post)) # Print column names of data_post for debugging

  # Create boxplot with significance annotations and beeswarm overlay
  box_plot_post <- ggboxplot(data_post, x = "bins", y = "num_clones", fill = type) +
    stat_pvalue_manual(stat_test, label = "p.adj.signif", tip.length = 0.01, step.increase = 0.00, bracket.nudge.y = -1, size = 8) +
    geom_beeswarm(data = data_post_n0, position = "dodge", dodge.width = .75, na.rm = TRUE, aes(x = bins, y = num_clones, group = .data[[type]])) +
    scale_y_continuous(trans = 'log10', labels = scales::number_format(accuracy = 0.0001)) +
    theme_pubr() +
    theme(
      text = element_text(size = text_size),
      axis.text.x = element_text(angle = 45, hjust = 1),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(color = "black"),
      axis.ticks.length = unit(0.25, "cm"),
      legend.text = element_markdown()
    ) +
    labs(y = ylab, title = title, x = "Days")

  # Prepare data for output
  data_post <- data_post %>%
    mutate(timepoint = as.character(timepoint))
  data <- bind_rows(data_post)

  return(list(box_plot_post, wilcox_results, data)) # Return boxplot, Wilcoxon test results, and processed data
}

```

```{r, warning=FALSE, fig.width=9.5, fig.height = 5}

data_CD48_all_expand_adj <- data_CD48_all_expand
data_CD48_all_expand_adj$cell_type <- gsub(" ", "",data_CD48_all_expand_adj$cell_type )
data_CD48_all_expand_adj <- dplyr::full_join(data_CD48_all_expand_adj, clinical_data, by = "PatientID")
data_CD48_all_expand_adj <- data_CD48_all_expand_adj%>%
  mutate(GVHD_GRADE_1 = ifelse(grepl("Severe", GVHD_GRADE_1), "Severe", GVHD_GRADE_1))

if(remove_pat_regx != ""){
  data_CD48_all_expand_adj <- data_CD48_all_expand_adj[!grepl(remove_pat_regx,data_CD48_all_expand_adj$PatientID),]
}

data_CD48_all_expand_adj <- data_CD48_all_expand_adj%>%
  mutate(GVHD_GRADE_1 = ifelse(grepl("No|Mild", GVHD_GRADE_1), "No/Mild", "Severe"))#%>%
  #mutate(GVHD_GRADE_1 = factor(GVHD_GRADE_1, levels = c("No/Mild", "Severe")))

type <- "GVHD_GRADE_1"


result_NoPTCy <- num_clones(subset(data_CD48_all_expand_adj, data_CD48_all_expand_adj$PTCy == "No PTCy"), type, num_cuts = 4, title = "No PTCy No and Mild vs Severe", ylab = "Alloreactive \n Cumulative Frequency")
NoPTCy <- result_NoPTCy[[1]]+
  scale_fill_manual(name = "GVHD Grade", values=c("#058b8e", "#B85000"),
                    labels = c(
      `No/Mild` = "<span style='color:#058b8e;'>No/Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))
test_NoPTCy <- result_NoPTCy[[2]]

result_PTCy <- num_clones(subset(data_CD48_all_expand_adj, data_CD48_all_expand_adj$PTCy == "PTCy"), type, num_cuts=4, title = "PTCy No and Mild vs Severe", ylab = "Alloreactive \n Cumulative Frequency")
PTCy <- result_PTCy[[1]]+
  scale_fill_manual(name = "GVHD Grade", values=c("#058b8e", "#B85000"),
                    labels = c(
      `No/Mild` = "<span style='color:#058b8e;'>No/Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))
test_PTCy <- result_PTCy[[2]]

result_All_byPTCy <- num_clones(data_CD48_all_expand_adj, "PTCy", num_cuts = 4, title = "PTCy vs No PTCy", ylab = "Alloreactive \n Cumulative Frequency")
All_byPTCy <- result_All_byPTCy[[1]]+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"),
                    labels = c(
      `No PTCy` = "<span style='color:#E6BE60;'>No PTCy</span>",
      PTCy = "<span style='color:#A483AF;'>PTCy</span>"))
test_All_byPTCy <- result_All_byPTCy[[2]]

result_Grade_byPTCy <- num_clones(data_CD48_all_expand_adj, type, num_cuts = 4, title = "", ylab = "Alloreactive \n Cumulative Frequency")
Grade_byPTCy <- result_Grade_byPTCy[[1]]+
  scale_fill_manual(name = "GVHD Grade", values = c("#058b8e", "#B85000"),
                    labels = c(
      `No/Mild` = "<span style='color:#058b8e;'>No/Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))
test_Grade_byPTCy <- result_Grade_byPTCy[[2]]

data_CD48_all_expand_adj_CD4 <- data_CD48_all_expand_adj%>%
  filter(grepl("CD4",cell_type) & !grepl("CD8", cell_type))

data_CD48_all_expand_adj_CD8 <- data_CD48_all_expand_adj%>%
  filter(!grepl("CD4",cell_type) & grepl("CD8", cell_type))

result_Grade_byPTCy <- num_clones(data_CD48_all_expand_adj_CD4, type, num_cuts = 2, title = "GVHD Grade CD4+", ylab = "Alloreactive \n Cumulative Frequency")
Grade_byPTCy_CD4 <- result_Grade_byPTCy[[1]]+
  scale_fill_manual(name = "GVHD Grade", values = c("#058b8e", "#B85000"),
                    labels = c(
      `No/Mild` = "<span style='color:#058b8e;'>No/Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))
result_Grade_byPTCy <- num_clones(data_CD48_all_expand_adj_CD8, type, num_cuts = 2, title = "GVHD Grade CD8+", ylab = "Alloreactive \n Cumulative Frequency")
Grade_byPTCy_CD8 <- result_Grade_byPTCy[[1]]+
  scale_fill_manual(name = "GVHD Grade", values = c("#058b8e", "#B85000"),
                    labels = c(
      `No/Mild` = "<span style='color:#058b8e;'>No/Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))

result_CD4_byPTCy <- num_clones(data_CD48_all_expand_adj_CD4, "PTCy", num_cuts = 4, title = "PTCy vs No PTCy CD4+", ylab = "Alloreactive \n Cumulative Frequency")
CD4_byPTCy <- result_CD4_byPTCy[[1]]+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"),
                    labels = c(
      `No PTCy` = "<span style='color:#E6BE60;'>No PTCy</span>",
      PTCy = "<span style='color:#A483AF;'>PTCy</span>"))


result_CD8_byPTCy <- num_clones(data_CD48_all_expand_adj_CD8, "PTCy", num_cuts = 4, title = "PTCy vs No PTCy CD8+", ylab = "Alloreactive \n Cumulative Frequency")
CD8_byPTCy <- result_CD8_byPTCy[[1]]+
    scale_fill_manual(values = c("#E6BE60", "#A483AF"),
                    labels = c(
      `No PTCy` = "<span style='color:#E6BE60;'>No PTCy</span>",
      PTCy = "<span style='color:#A483AF;'>PTCy</span>"))




plot(Grade_byPTCy)
plot(Grade_byPTCy_CD4)
plot(Grade_byPTCy_CD8)
plot(NoPTCy)
plot(PTCy)
plot(All_byPTCy)

plot(CD4_byPTCy)
plot(CD8_byPTCy)
ggsave(paste0(OUTPUT_PATH, '/Figure1/Grade_byPTCy',type,'.png'), Grade_byPTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1/Grade_byPTCy_CD4',type,'.png'), Grade_byPTCy_CD4, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1/Grade_byPTCy_CD8',type,'.png'), Grade_byPTCy_CD8, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/all_NoPTCy',type,'.png'), NoPTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/all_PTCy',type,'.png'), PTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/all_All_byPTCy.png'), All_byPTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3ex/CD4_byPTCy',type,'.png'), CD4_byPTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3ex/CD8_byPTCy',type,'.png'), CD8_byPTCy, width = 9.5, height = 5, dpi = 600)


ggsave(paste0(OUTPUT_PATH, '/Figure1/Grade_byPTCy',type,'.pdf'), Grade_byPTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1/Grade_byPTCy_CD4',type,'.pdf'), Grade_byPTCy_CD4, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1/Grade_byPTCy_CD8',type,'.pdf'), Grade_byPTCy_CD8, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/all_NoPTCy',type,'.pdf'), NoPTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/all_PTCy',type,'.pdf'), PTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/all_All_byPTCy.pdf'), All_byPTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3ex/CD4_byPTCy',type,'.pdf'), CD4_byPTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3ex/CD8_byPTCy',type,'.pdf'), CD8_byPTCy, width = 9.5, height = 5, dpi = 600)


ggsave(paste0(OUTPUT_PATH, '/Figure1/Grade_byPTCy',type,'.svg'), Grade_byPTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/all_NoPTCy',type,'.svg'), NoPTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1/Grade_byPTCy_CD4',type,'.svg'), Grade_byPTCy_CD4, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1/Grade_byPTCy_CD8',type,'.svg'), Grade_byPTCy_CD8, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/all_PTCy',type,'.svg'), PTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/all_All_byPTCy.svg'), All_byPTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3ex/CD4_byPTCy',type,'.svg'), CD4_byPTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3ex/CD8_byPTCy',type,'.svg'), CD8_byPTCy, width = 9.5, height = 5, dpi = 600)
```


```{r nonallo-all-by-ptcy, warning=FALSE, fig.width=9.5, fig.height=5}

# Non-alloreactive equivalent of all_All_byPTCy
data_nonallo_expand_adj <- data_nonallo_squished_w0
data_nonallo_expand_adj$cell_type <- gsub(" ", "", data_nonallo_expand_adj$cell_type)
data_nonallo_expand_adj <- dplyr::full_join(data_nonallo_expand_adj, meta_data, by = "PatientID")
data_nonallo_expand_adj <- data_nonallo_expand_adj %>%
  mutate(GVHD_GRADE_1 = ifelse(grepl("Severe", GVHD_GRADE_1), "Severe", GVHD_GRADE_1))

if (remove_pat_regx != "") {
  data_nonallo_expand_adj <- data_nonallo_expand_adj[!grepl(remove_pat_regx, data_nonallo_expand_adj$PatientID), ]
}
data_nonallo_expand_adj <- data_nonallo_expand_adj[data_nonallo_expand_adj$PatientID != "R070", ]

data_nonallo_expand_adj <- data_nonallo_expand_adj %>%
  mutate(GVHD_GRADE_1 = ifelse(grepl("No|Mild", GVHD_GRADE_1), "No/Mild", "Severe"))

result_All_nonallo_byPTCy <- num_clones(data_nonallo_expand_adj, "PTCy", num_cuts = 4,
                                        title = "PTCy vs No PTCy (Non-Alloreactive)",
                                        ylab = "Non-Alloreactive \n Cumulative Frequency")
All_nonallo_byPTCy <- result_All_nonallo_byPTCy[[1]] +
  scale_fill_manual(values = c("#E6BE60", "#A483AF"),
                    labels = c(
                      `No PTCy` = "<span style='color:#E6BE60;'>No PTCy</span>",
                      PTCy = "<span style='color:#A483AF;'>PTCy</span>"))
test_All_nonallo_byPTCy <- result_All_nonallo_byPTCy[[2]]

plot(All_nonallo_byPTCy)

ggsave(paste0(OUTPUT_PATH, '/Figure3/all_All_nonallo_byPTCy.png'), All_nonallo_byPTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/all_All_nonallo_byPTCy.pdf'), All_nonallo_byPTCy, width = 9.5, height = 5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/all_All_nonallo_byPTCy.svg'), All_nonallo_byPTCy, width = 9.5, height = 5, dpi = 600)
```


```{r, warning=FALSE, fig.width=6, fig.height = 4}

# data_CD48_all$PTCy <- ifelse(grepl("PTCy", data_CD48_all$PTCy), "PTCy", "No PTCy")

data_CD48_all_expand_adj <- dplyr::full_join(data_CD48_all, clinical_data, by = 'PatientID')
data_CD48_all_expand_adj <- data_CD48_all_expand_adj[!is.na(data_CD48_all_expand_adj$cdr3_amino_acid),]
data_CD48_all_expand_adj <- data_CD48_all_expand_adj[!grepl("67",data_CD48_all_expand_adj$PatientID),]
data_CD48_all_expand_adj <- data_CD48_all_expand_adj[!grepl("70",data_CD48_all_expand_adj$PatientID),]

data_CD48_all_expand_adj <- data_CD48_all_expand_adj%>%
  mutate(GVHD_GRADE_1 = ifelse(grepl("Severe", GVHD_GRADE_1), "Severe", "No and Mild"))


if(remove_pat_regx != ""){
  data_CD48_all_expand_adj <- data_CD48_all_expand_adj[!grepl(remove_pat_regx,data_CD48_all_expand_adj$PatientID),]
}

data_CD48_all_expand_sel_PTCy <- subset(data_CD48_all_expand_adj, "PTCy" == data_CD48_all_expand_adj$PTCy)
data_CD48_all_expand_sel_noPTCy <- subset(data_CD48_all_expand_adj, "No PTCy" == data_CD48_all_expand_adj$PTCy)


BothPTCy_CD4_data <- subset(data_CD48_all_expand_adj,!grepl('CD4CD8',data_CD48_all_expand_adj$cell_type) & grepl('CD4',data_CD48_all_expand_adj$cell_type))

BothPTCy_CD8_data <- subset(data_CD48_all_expand_adj,!grepl('CD4CD8',data_CD48_all_expand_adj$cell_type) & grepl('CD8',data_CD48_all_expand_adj$cell_type))

BothPTCy_CD4_results <- num_clones(BothPTCy_CD4_data, "PTCy", num_cuts = 4, title = "Both PTCy CD4", ylab ="Alloreactive \n Cumulative Frequency")
BothPTCy_CD4 <- BothPTCy_CD4_results[[1]]+
  scale_fill_manual(values=c("#E6BE60", "#A483AF"))+
  # scale_color_manual(values=c("#E6BE60", "#A483AF"))+
  labs(title = "No PTCy vs PTCy CD4")
test_BothPTCy_CD4 <- BothPTCy_CD4_results[[2]]
BothPTCy_CD4_data_res <- BothPTCy_CD4_results[[3]]

BothPTCy_CD8_results <- num_clones(BothPTCy_CD8_data, "PTCy", num_cuts = 4, title = "Both PTCy CD8", ylab = "Alloreactive \n Cumulative Frequency")
BothPTCy_CD8 <- BothPTCy_CD8_results[[1]]+
  scale_fill_manual(values=c("#E6BE60", "#A483AF"))+
  # scale_color_manual(values=c("#E6BE60", "#A483AF"))+
  labs(title = "No PTCy vs PTCy CD8")
test_BothPTCy_CD8 <- BothPTCy_CD8_results[[2]]
BothPTCy_CD8_data_res <- BothPTCy_CD8_results[[3]]

type = "GVHD_GRADE_1"

BothPTCy_CD4_results_g <- num_clones(BothPTCy_CD4_data, type, num_cuts = 4, title = "No and Mild vs. Severe CD4", ylab = "Alloreactive \n Cumulative Frequency")
BothPTCy_CD4_g <- BothPTCy_CD4_results_g[[1]]+
  scale_fill_manual(values=c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))
test_BothPTCy_CD4_g <- BothPTCy_CD4_results_g[[2]]
BothPTCy_CD4_data_g <- BothPTCy_CD4_results_g[[3]]

BothPTCy_CD8_results_g <- num_clones(BothPTCy_CD8_data, type, num_cuts = 4, title = "No and Mild vs. Severe CD8", ylab = "Alloreactive \n Cumulative Frequency")
BothPTCy_CD8_g <- BothPTCy_CD8_results_g[[1]]+
  scale_fill_manual(values=c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))
test_BothPTCy_CD8_g <- BothPTCy_CD8_results_g[[2]]
BothPTCy_CD8_data_g <- BothPTCy_CD8_results_g[[3]]

NoPTCy_CD4_data <- subset(data_CD48_all_expand_sel_noPTCy,!grepl('CD4CD8',data_CD48_all_expand_sel_noPTCy$cell_type) & grepl('CD4',data_CD48_all_expand_sel_noPTCy$cell_type))
NoPTCy_CD8_data <- subset(data_CD48_all_expand_sel_noPTCy,!grepl('CD4CD8',data_CD48_all_expand_sel_noPTCy$cell_type) & grepl('CD8',data_CD48_all_expand_sel_noPTCy$cell_type))
PTCy_CD4_data <- subset(data_CD48_all_expand_sel_PTCy,!grepl('CD4CD8',data_CD48_all_expand_sel_PTCy$cell_type) & grepl('CD4',data_CD48_all_expand_sel_PTCy$cell_type))
PTCy_CD8_data <- subset(data_CD48_all_expand_sel_PTCy,!grepl('CD4CD8',data_CD48_all_expand_sel_PTCy$cell_type) & grepl('CD8',data_CD48_all_expand_sel_PTCy$cell_type))

num_cuts <- 4

NoPTCy_CD4_results <- num_clones(NoPTCy_CD4_data, type, num_cuts = num_cuts, title = "NoPTCy No and Mild vs. Severe CD4+", ylab = "Alloreactive \n Cumulative Frequency")
NoPTCy_CD4 <- NoPTCy_CD4_results[[1]]+
  labs(title = "No PTCy No and Mild vs. Severe CD4+")+
  scale_fill_manual(values=c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))
test_NoPTCy_CD4 <- NoPTCy_CD4_results[[2]]
NoPTCy_CD4_data <- NoPTCy_CD4_results[[3]]

NoPTCy_CD8_results <- num_clones(NoPTCy_CD8_data, type, num_cuts = num_cuts, title = "NoPTCy No and Mild vs. Severe CD8+", ylab = "Alloreactive \n Cumulative Frequency")
NoPTCy_CD8 <- NoPTCy_CD8_results[[1]]+
  labs(title = "No PTCy No and Mild vs. Severe CD8+")+
  scale_fill_manual(values=c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))
test_NoPTCy_CD8 <- NoPTCy_CD8_results[[2]]
NoPTCy_CD8_data <-NoPTCy_CD8_results[[3]]

PTCy_CD4_results <- num_clones(PTCy_CD4_data, type, num_cuts = num_cuts, title = "PTCy No and Mild vs. Severe CD4+", ylab = "Alloreactive \n Cumulative Frequency")
PTCy_CD4 <- PTCy_CD4_results[[1]]+
  labs(title = "PTCy No and Mild vs. Severe CD4+")+
  scale_fill_manual(values=c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))
test_PTCy_CD4 <- PTCy_CD4_results[[2]]
PTCy_CD4_data <- PTCy_CD4_results[[3]]


PTCy_CD8_results <- num_clones(PTCy_CD8_data, type, num_cuts = num_cuts, title = "PTCy No and Mild vs. Severe CD8+", ylab = "Alloreactive \n Cumulative Frequency")
test_PTCy_CD8 <- PTCy_CD8_results[[2]]
PTCy_CD8_data <- PTCy_CD8_results[[3]]

PTCy_CD8 <- PTCy_CD8_results[[1]]+
  labs(title = "PTCy No and Mild vs. Severe CD8+")+
  scale_fill_manual(values=c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))

plot(BothPTCy_CD4)
plot(BothPTCy_CD8)
plot(BothPTCy_CD4_g)
plot(BothPTCy_CD8_g)
plot(NoPTCy_CD4)
plot(NoPTCy_CD8)
plot(PTCy_CD4)
plot(PTCy_CD8)

ggsave(paste0(OUTPUT_PATH, '/Figure3/BothPTCy_CD4_all_',type,'.png'), BothPTCy_CD4,  width = 6, height = 3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/BothPTCy_CD8_all_',type,'.png'), BothPTCy_CD8, width = 6, height = 3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1/BothPTCy_CD4_all_',type,'.png'), BothPTCy_CD4_g,  width = 6, height = 3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1/BothPTCy_CD8_all_',type,'.png'), BothPTCy_CD8_g, width = 6, height = 3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/NoPTCy_CD4_all_',type,'.png'), NoPTCy_CD4, width = 6, height = 3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/NoPTCy_CD8_all_',type,'.png'), NoPTCy_CD8,  width = 6, height = 3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/PTCy_CD4_all_',type,'.png'), PTCy_CD4, width = 6, height = 3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/PTCy_CD8_all_',type,'.png'), PTCy_CD8, width = 6, height = 3, dpi = 600)

ggsave(paste0(OUTPUT_PATH, '/Figure3/BothPTCy_CD4_all_',type,'.pdf'), BothPTCy_CD4,  width = 6, height = 3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/BothPTCy_CD8_all_',type,'.pdf'), BothPTCy_CD8, width = 6, height = 3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1/BothPTCy_CD4_all_',type,'.pdf'), BothPTCy_CD4_g,  width = 6, height = 3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1/BothPTCy_CD8_all_',type,'.pdf'), BothPTCy_CD8_g, width = 6, height = 3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/NoPTCy_CD4_all_',type,'.pdf'), NoPTCy_CD4, width = 6, height = 3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/NoPTCy_CD8_all_',type,'.pdf'), NoPTCy_CD8,  width = 6, height = 3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/PTCy_CD4_all_',type,'.pdf'), PTCy_CD4, width = 6, height = 3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/PTCy_CD8_all_',type,'.pdf'), PTCy_CD8, width = 6, height = 3, dpi = 600)

#KEEP IN MIND
```

```{r, warning=FALSE, fig.width=9.5, fig.height = 15}
# fig_EF combines plots from notebook 02 and this notebook
freq_Both_vio_ex <- readRDS(file.path(PROCESSED_DATA_PATH, "freq_Both_vio_ex.rds"))

fig_EF <- plot_grid(freq_Both_vio_ex, Grade_byPTCy, All_by_grade_fig_ex, ncol = 1, align = "v")
plot(fig_EF)

ggsave(paste0(OUTPUT_PATH, '/Figure1/fig_EF.pdf'), fig_EF, width = 9.5, height = 15, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1/fig_EF.png'), fig_EF, width = 9.5, height = 15, dpi = 600)

```

```{r save-objects}
# Save key objects for downstream use
saveRDS(Grade_byPTCy, file.path(PROCESSED_DATA_PATH, "Grade_byPTCy.rds"))
saveRDS(All_by_grade_fig_ex, file.path(PROCESSED_DATA_PATH, "All_by_grade_fig_ex.rds"))

cat("03_grade_ptcy_analysis objects saved successfully.\n")
```
