---
title: "04 - Cumulative Figures"
output: html_document
---

```{r setup}
source(file.path(dirname(getwd()), "config", "config.R"))
source(file.path(dirname(getwd()), "functions", "mlr_functions.R"))

# Load data from previous notebooks
data <- readRDS(file.path(PROCESSED_DATA_PATH, "patient_data_all.rds"))
data_allo <- readRDS(file.path(PROCESSED_DATA_PATH, "patient_data_allo.rds"))
data_nonallo <- readRDS(file.path(PROCESSED_DATA_PATH, "data_nonallo_list.rds"))
data_meta <- readRDS(file.path(PROCESSED_DATA_PATH, "data_meta.rds"))
all_full_allo <- readRDS(file.path(PROCESSED_DATA_PATH, "all_full_allo.rds"))
filenames <- readRDS(file.path(PROCESSED_DATA_PATH, "filenames.rds"))
clinical_data <- readRDS(file.path(PROCESSED_DATA_PATH, "clinical_data_full.rds"))
data_squished <- readRDS(file.path(PROCESSED_DATA_PATH, "data_squished.rds"))
data_squished_w0 <- readRDS(file.path(PROCESSED_DATA_PATH, "data_squished_w0.rds"))
data_allo_squished <- readRDS(file.path(PROCESSED_DATA_PATH, "data_allo_squished.rds"))
data_allo_squished_w0 <- readRDS(file.path(PROCESSED_DATA_PATH, "data_allo_squished_w0.rds"))
data_nonallo_squished <- readRDS(file.path(PROCESSED_DATA_PATH, "data_nonallo_squished.rds"))
data_nonallo_squished_w0 <- readRDS(file.path(PROCESSED_DATA_PATH, "data_nonallo_squished_w0.rds"))
meta_data_clin <- readRDS(file.path(PROCESSED_DATA_PATH, "meta_data_clin.rds"))
meta_data <- readRDS(file.path(PROCESSED_DATA_PATH, "meta_data.rds"))
expanded_clones <- readRDS(file.path(PROCESSED_DATA_PATH, "expanded_clones.rds"))
data_CD48_all <- readRDS(file.path(PROCESSED_DATA_PATH, "data_CD48_all.rds"))
data_CD48_all_expand <- readRDS(file.path(PROCESSED_DATA_PATH, "data_CD48_all_expand.rds"))
patient_data_all <- readRDS(file.path(PROCESSED_DATA_PATH, "patient_data_all_df.rds"))
data_squished_time <- readRDS(file.path(PROCESSED_DATA_PATH, "data_squished_time.rds"))
patient_data_all_2 <- readRDS(file.path(PROCESSED_DATA_PATH, "patient_data_all_2.rds"))
unique_identifiers <- c("cdr3_amino_acid", "v_resolved", "j_resolved")
remove_pat_regx <- ""  # set to e.g. "067|070" to exclude patients
data_all_squished  <- readRDS(file.path(PROCESSED_DATA_PATH, "data_all_squished_proc.rds"))
all_rep_div        <- readRDS(file.path(PROCESSED_DATA_PATH, "all_rep_div.rds"))
all_allo_div       <- readRDS(file.path(PROCESSED_DATA_PATH, "all_allo_div.rds"))
all_allo_div_CD4   <- readRDS(file.path(PROCESSED_DATA_PATH, "all_allo_div_CD4.rds"))
all_allo_div_CD8   <- readRDS(file.path(PROCESSED_DATA_PATH, "all_allo_div_CD8.rds"))
all_nonallo_div    <- readRDS(file.path(PROCESSED_DATA_PATH, "all_nonallo_div.rds"))
all_nonallo_div_CD4 <- readRDS(file.path(PROCESSED_DATA_PATH, "all_nonallo_div_CD4.rds"))
all_nonallo_div_CD8 <- readRDS(file.path(PROCESSED_DATA_PATH, "all_nonallo_div_CD8.rds"))
```

```{r}
div_clones <- function(data, type, div_metric = "shannons.entropy", num_cuts = 5){
  #' Divide clones based on timepoints and diversity metric
  #'
  #' @description This function processes a dataset of clones to divide it into pre- and post-stimulation data based on specific timepoints. The function filters and bins data to analyze clonal diversity using a specified diversity metric.
  #'
  #' @param data A dataframe containing clone data, including a `SampleID` column which indicates timepoints or conditions.
  #' @param type A character string specifying the type of analysis or dataset being processed.
  #' @param div_metric A character string specifying the diversity metric to use (default is "shannons.entropy").
  #' @param num_cuts An integer indicating the number of bins to divide the timepoints into (default is 5).
  #' @usage div_clones(data, type, div_metric, num_cuts)
  #' @return A list containing two dataframes: `data_pre` for pre-stimulation and `data_post` for post-stimulation data.

  data_pre <- data[grepl("MLR|unstim", data$SampleID),]%>%
    dplyr::mutate(timepoint = SampleID) # Filter for pre-stimulation samples and mutate timepoint to be the same as SampleID

  data_proc <- data %>%
    dplyr::mutate(timepoint = strtoi(SampleID)) # Convert SampleID to an integer timepoint for processing
  data_proc <- data_proc[!is.na(data_proc$timepoint),] # Remove any rows where timepoint conversion was not possible (NA values)

  data_post <- data_proc[data_proc$timepoint <= 365 & data_proc$timepoint > 3,] %>%
    ungroup() %>%
    dplyr::mutate(bins = cut(timepoint, breaks = unique(quantile(timepoint, probs = 0:num_cuts/num_cuts)), include.lowest = TRUE)) # Filter for post-stimulation samples within a year and create bins based on timepoints

  return(list(data_pre, data_post)) # Return a list containing pre- and post-stimulation dataframes
}


div_cut <- function(data, type, div_metric = "shannons.entropy", num_cuts = 5, text_size = 20, ylab = "", title = ""){
  #' Analyze diversity metrics and visualize results
  #'
  #' @description This function calculates diversity metrics for different bins of timepoints, performs pairwise Wilcoxon tests, and visualizes the results using boxplots with significance annotations.
  #'
  #' @param data A dataframe containing clone data, including a `SampleID` column.
  #' @param type A character string specifying the grouping variable for the analysis.
  #' @param div_metric A character string specifying the diversity metric to use (default is "shannons.entropy").
  #' @param num_cuts An integer indicating the number of bins to divide the timepoints into (default is 5).
  #' @param text_size An integer specifying the size of text in the plot (default is 20).
  #' @param ylab A character string for the y-axis label in the plot.
  #' @param title A character string for the plot title.
  #' @usage div_cut(data, type, div_metric, num_cuts, text_size, ylab, title)
  #' @return A list containing the boxplot with significance annotations, the Wilcoxon test results, and the processed data.

  results <- div_clones(data, type, div_metric, num_cuts)
  data_pre <- results[[1]]
  data_post <- results[[2]]

  print(unique(data_pre[[type]])) # Print unique values of the grouping variable in pre-stimulation data

  # Summarize post-stimulation data by bins and grouping variable
  data_post_sum <- data_post %>%
    group_by(across(all_of(c("bins", type)))) %>%
    summarise(n_each = n())

  # Perform pairwise Wilcoxon test and add positions for significance annotations
  stat_test <- data_post %>%
    group_by(bins) %>%
    pairwise_wilcox_test(as.formula(paste0(div_metric, " ~ ", type)), p.adjust.method = "hochberg") %>%
    rstatix::add_xy_position(x = "bins")

  # Create boxplot with beeswarm overlay and significance annotations
  box_plot_post <- ggboxplot(data_post, x = "bins", y = div_metric, fill = type, outlier.shape = NA) +
    stat_pvalue_manual(stat_test, label = "p.adj.signif", tip.length = 0.01, step.increase = 0.001) +
    geom_beeswarm(position = "dodge", dodge.width = .75, aes(group = .data[[type]])) +
    scale_y_continuous(labels = scales::number_format(accuracy = 1))+
    theme_pubr() +
    theme(
      legend.text = element_markdown(),
      text = element_text(size = text_size),
      axis.text.x = element_text(angle = 45, hjust = 1),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      axis.line = element_line(color = "black"),
      axis.ticks = element_blank(),
      axis.ticks.length = unit(0.25, "cm")
    ) +
    labs(y = ylab, title = title)

  return(list(box_plot_post, stat_test, data_post)) # Return boxplot, statistical test results, and processed post-stimulation data
}

```

```{r, warning=FALSE, fig.width=8, fig.height = 4}

patient_data_allo_copy <- patient_data_all[patient_data_all$Rep_div == "allo", ]

patient_data_all_clinic <- dplyr::full_join(patient_data_allo_copy, meta_data_clin, by = "PatientID")%>%
  try(mutate(PTCy = PTCy.x))%>%
  try(select(-c(PTCy.x, PTCy.y)))%>%
  mutate(GVHD_GRADE_1 = ifelse(grepl("Severe", GVHD_GRADE_1), "Severe", "No and Mild"))%>%
  mutate(GVHD_GRADE_1 = factor(GVHD_GRADE_1, levels = c("No and Mild", "Severe")))
patient_data_all_clinic <- patient_data_all_clinic[patient_data_all_clinic$GVHD_GRADE_1 != "Unclassified/Severe",]
patient_data_all_clinic <- patient_data_all_clinic[!is.na(patient_data_all_clinic$slope),]

if(remove_pat_regx != ""){
  patient_data_all_clinic <- patient_data_all_clinic[!grepl(remove_pat_regx,patient_data_all_clinic$PatientID),]
}


type <- "GVHD_GRADE_1"


result_Both <- div_cut(patient_data_all_clinic, type, num_cuts = 4, div_metric ="shannons.diversity" , ylab = "Shannon's Diversity",)
Both <- result_Both[[1]]+
  scale_fill_manual(name = "GVHD Grade", values = c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))+
  labs(x = "Days", title = "No and Mild vs Severe")
test_BothPTCy <- result_Both[[2]]


result_NoPTCy <- div_cut(subset(patient_data_all_clinic, patient_data_all_clinic$PTCy == "No PTCy"), type, num_cuts = 4, div_metric ="shannons.diversity" , ylab = "Shannon's Diversity",)
NoPTCy <- result_NoPTCy[[1]]+
  scale_fill_manual(name = "GVHD Grade",values = c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))+
  labs(x = "Days", title = "No PTCy: No and Mild vs Severe")
test_NoPTCy <- result_NoPTCy[[2]]


result_PTCy <- div_cut(subset(patient_data_all_clinic, patient_data_all_clinic$PTCy == "PTCy"), type, num_cuts = 4, div_metric ="shannons.diversity" , ylab = "Shannon's Diversity",)
PTCy <- result_PTCy[[1]]+
  scale_fill_manual(name = "GVHD Grade", values = c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))+
  labs(x = "Days", title = "PTCy: No and Mild vs Severe")
test_PTCy <- result_PTCy[[2]]

result_All_byPTCy <- div_cut(patient_data_all_clinic[patient_data_all_clinic$PatientID != "R070",], "PTCy", num_cuts = 4, div_metric ="shannons.diversity" , ylab = "Shannon's Diversity", title = "PTCy vs No PTCy")
All_byPTCy <- result_All_byPTCy[[1]]+
  scale_fill_manual(values = c("#E6BE60", "#A483AF"),
                    labels = c(
      `No PTCy` = "<span style='color:#E6BE60;'>No PTCy</span>",
      PTCy = "<span style='color:#A483AF;'>PTCy</span>"))+
  labs(x = "Days")

test_All_byPTCy <- result_All_byPTCy[[2]]



plot(Both)
plot(NoPTCy)
plot(PTCy)
plot(All_byPTCy)

ggsave(paste0(OUTPUT_PATH, '/Figure1ex/Grade_Shannon_',type,'.png'), Both, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/Grade_Shannon_', type,'.pdf'), Both, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/Grade_Shannon_', type,'.svg'), Both, width = 8, height = 4, dpi = 600)

ggsave(paste0(OUTPUT_PATH, '/Figure1ex/GradeNoPTCy_Shannon_',type,'.png'), NoPTCy,width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/GradeNoPTCy_Shannon_', type,'.pdf'), NoPTCy,width = 8, height = 4, dpi = 600)

ggsave(paste0(OUTPUT_PATH, '/Figure1ex/GradePTCy_Shannon_',type,'.png'), PTCy, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/GradePTCy_Shannon_', type,'.pdf'), PTCy, width = 8, height = 4, dpi = 600)

ggsave(paste0(OUTPUT_PATH, '/Figure3/ByPTCy_Shannon_',type,'.png'), All_byPTCy, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/ByPTCy_Shannon_', type,'.pdf'), All_byPTCy, width = 8, height = 4, dpi = 600)



```


```{r, fig.width = 8 , fig.height = 4}
patient_data_allo_CD4 <-bind_rows(all_allo_div_CD4)%>%
  subset(!is.na(slope))%>%
  mutate(cell_type = "CD4", PatientID = str_split_fixed(ID, "_", 3)[,1], SampleID = str_split_fixed(ID, "_", 3)[,2])
patient_data_allo_CD8 <-bind_rows(all_allo_div_CD8)%>%
  subset(!is.na(slope))%>%
  mutate(cell_type = "CD8", PatientID = str_split_fixed(ID, "_", 3)[,1], SampleID = str_split_fixed(ID, "_", 3)[,2])

patient_data_allo_CD48 <- bind_rows(patient_data_allo_CD8, patient_data_allo_CD4)
patient_data_allo_CD48 <- dplyr::inner_join(patient_data_allo_CD48, meta_data_clin, by = "PatientID")

if(remove_pat_regx != ""){
  patient_data_all_clinic <- patient_data_all_clinic[!grepl(remove_pat_regx,patient_data_all_clinic$PatientID),]
}
patient_data_allo_CD48_clinic <- patient_data_allo_CD48#[!grepl("70",patient_data_allo_CD48$PatientID),]


patient_data_allo_CD48_clinic <- patient_data_allo_CD48_clinic%>%
  filter(PatientID != "R070")%>%
  mutate(GVHD_GRADE_1 = ifelse(grepl("Severe", GVHD_GRADE_1), "Severe", "No and Mild"))%>%
  mutate(GVHD_GRADE_1 = factor(GVHD_GRADE_1, levels = c("No and Mild", "Severe")))

patient_data_allo_CD48_clinic$GVHD_GRADE_2 <- factor(patient_data_allo_CD48_clinic$GVHD_GRADE_2, levels = c("Mild", "Moderate", "Severe"))
patient_data_allo_CD48_clinic_CD4 <- subset(patient_data_allo_CD48_clinic, grepl("4",patient_data_allo_CD48_clinic$cell_type))
patient_data_allo_CD48_clinic_CD8 <- subset(patient_data_allo_CD48_clinic, grepl("8",patient_data_allo_CD48_clinic$cell_type))
patient_data_allo_CD48_clinic_PTCy <- subset(patient_data_allo_CD48_clinic, "PTCy" == patient_data_allo_CD48_clinic$PTCy)
patient_data_allo_CD48_clinic_noPTCy <- subset(patient_data_allo_CD48_clinic, "PTCy" != patient_data_allo_CD48_clinic$PTCy)


n = 4


BothPTCy_CD4_results <- div_cut(patient_data_allo_CD48_clinic_CD4, "PTCy", num_cuts = n, ylab = "Shannon's Diversity", div_metric = "shannons.diversity")
BothPTCy_CD4 <- BothPTCy_CD4_results[[1]]+
  scale_fill_manual(values = c("#E6BE60", "#A483AF"),
                    labels = c(
      `No PTCy` = "<span style='color:#E6BE60;'>No PTCy</span>",
      PTCy = "<span style='color:#A483AF;'>PTCy</span>"))+
  labs(title = "No PTCy vs PTCy CD4", x = "Days")+
  theme(legend.position = "none")
test_BothPTCy_CD4 <- BothPTCy_CD4_results[[2]]
BothPTCy_CD4_data <- BothPTCy_CD4_results[[3]]

BothPTCy_CD8_results <- div_cut(patient_data_allo_CD48_clinic_CD8, "PTCy", num_cuts = n, ylab = "Shannon's Diversity", div_metric = "shannons.diversity")
BothPTCy_CD8 <- BothPTCy_CD8_results[[1]]+
  scale_fill_manual(values = c("#E6BE60", "#A483AF"),
                    labels = c(
      `No PTCy` = "<span style='color:#E6BE60;'>No PTCy</span>",
      PTCy = "<span style='color:#A483AF;'>PTCy</span>"))+
  labs(title = "No PTCy vs PTCy CD8", x = "Days")+
  theme(legend.position = "none")
test_BothPTCy_CD8 <- BothPTCy_CD8_results[[2]]
BothPTCy_CD8_data <- BothPTCy_CD8_results[[3]]

plot(BothPTCy_CD4)
plot(BothPTCy_CD8)

ggsave(paste0(OUTPUT_PATH, '/Figure3/BothPTCy_CD4.png'), BothPTCy_CD4, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/BothPTCy_CD8.png'), BothPTCy_CD8, width = 8, height = 4, dpi = 600)

ggsave(paste0(OUTPUT_PATH, '/Figure3/BothPTCy_CD4.pdf'), BothPTCy_CD4, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/BothPTCy_CD8.pdf'), BothPTCy_CD8, width = 8, height = 4, dpi = 600)

ggsave(paste0(OUTPUT_PATH, '/Figure3/BothPTCy_CD4.svg'), BothPTCy_CD4, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/BothPTCy_CD8.svg'), BothPTCy_CD8, width = 8, height = 4, dpi = 600)

type = "GVHD_GRADE_1"

num_cuts <- 2

BothPTCy_CD4_results <- div_cut(patient_data_allo_CD48_clinic_CD4, type, num_cuts = num_cuts, ylab = "Shannon's Diversity", div_metric = "shannons.diversity")
BothPTCy_CD4 <- BothPTCy_CD4_results[[1]]+
  scale_fill_manual(name = "GVHD Grade", values = c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))+
  labs(title = "No and Mild vs Severe CD4+", x = "Days")
test_BothPTCy_CD4 <- BothPTCy_CD4_results[[2]]
BothPTCy_CD4_data <- BothPTCy_CD4_results[[3]]

BothPTCy_CD8_results <- div_cut(patient_data_allo_CD48_clinic_CD8, type, num_cuts = num_cuts, ylab = "Shannon's Diversity", div_metric = "shannons.diversity")
BothPTCy_CD8 <- BothPTCy_CD8_results[[1]]+
  scale_fill_manual(name = "GVHD Grade", values = c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))+
  labs(title = "No and Mild vs Severe CD8+", x = "Days")
test_BothPTCy_CD8 <- BothPTCy_CD8_results[[2]]
BothPTCy_CD8_data <- BothPTCy_CD8_results[[3]]

NoPTCy_CD4_data <- subset(patient_data_allo_CD48_clinic_noPTCy,!grepl('CD4CD8',patient_data_allo_CD48_clinic_noPTCy$cell_type) & grepl('CD4',patient_data_allo_CD48_clinic_noPTCy$cell_type))

NoPTCy_CD8_data <- subset(patient_data_allo_CD48_clinic_noPTCy,!grepl('CD4CD8',patient_data_allo_CD48_clinic_noPTCy$cell_type) & grepl('CD8',patient_data_allo_CD48_clinic_noPTCy$cell_type))

PTCy_CD4_data <- subset(patient_data_allo_CD48_clinic_PTCy,!grepl('CD4CD8',patient_data_allo_CD48_clinic_PTCy$cell_type) & grepl('CD4',patient_data_allo_CD48_clinic_PTCy$cell_type))

PTCy_CD8_data <- subset(patient_data_allo_CD48_clinic_PTCy,!grepl('CD4CD8',patient_data_allo_CD48_clinic_PTCy$cell_type) & grepl('CD8',patient_data_allo_CD48_clinic_PTCy$cell_type))


NoPTCy_CD4_results <- div_cut(NoPTCy_CD4_data, type, num_cuts = num_cuts)
NoPTCy_CD4 <- NoPTCy_CD4_results[[1]]+
  scale_fill_manual(name = "GVHD Grade", values = c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))+
  labs(title = "No PTCy CD4", x = "Days")
test_NoPTCy_CD4 <- NoPTCy_CD4_results[[2]]
NoPTCy_CD4_data <- NoPTCy_CD4_results[[3]]

NoPTCy_CD8_results <- div_cut(NoPTCy_CD8_data, type, num_cuts = num_cuts, ylab = "Shannon's Diversity", div_metric = "shannons.diversity")
NoPTCy_CD8 <- NoPTCy_CD8_results[[1]]+
  scale_fill_manual(name = "GVHD Grade", values = c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))+
  labs(title = "No PTCy CD8", x = "Days")
test_NoPTCy_CD8 <- NoPTCy_CD8_results[[2]]
NoPTCy_CD8_data <-NoPTCy_CD8_results[[3]]

PTCy_CD4_results <- div_cut(PTCy_CD4_data, type, num_cuts = num_cuts, ylab = "Shannon's Diversity", div_metric = "shannons.diversity")
PTCy_CD4 <- PTCy_CD4_results[[1]]+
  scale_fill_manual(name = "GVHD Grade", values = c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))+
  labs(title = "PTCy CD4", x = "Days")
test_PTCy_CD4 <- PTCy_CD4_results[[2]]
PTCy_CD4_data <- PTCy_CD4_results[[3]]


PTCy_CD8_results <- div_cut(PTCy_CD8_data, type, num_cuts = num_cuts, ylab = "Shannon's Diversity", div_metric = "shannons.diversity")
PTCy_CD8 <- PTCy_CD8_results[[1]]+
  scale_fill_manual(name = "GVHD Grade", values = c("#058b8e", "#B85000", "grey"),
                    labels = c(
      `No and Mild` = "<span style='color:#058b8e;'>No and Mild</span>",
      Severe = "<span style='color:#B85000;'>Severe</span>"))+
  labs(title = "PTCy CD8", x = "Days")
test_PTCy_CD8 <- PTCy_CD8_results[[2]]
PTCy_CD8_data <- PTCy_CD8_results[[3]]

plot(BothPTCy_CD4)
plot(BothPTCy_CD8)
plot(NoPTCy_CD4)
plot(NoPTCy_CD8)
plot(PTCy_CD4)
plot(PTCy_CD8)

ggsave(paste0(OUTPUT_PATH, '/Figure1ex/BothPTCy_CD4_shannons',type,'.png'), BothPTCy_CD4, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/BothPTCy_CD8_shannons',type,'.png'), BothPTCy_CD8, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/NoPTCy_CD4_shannons',type,'.png'), NoPTCy_CD4, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/NoPTCy_CD8_shannons',type,'.png'), NoPTCy_CD8, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/PTCy_CD4_shannons',type,'.png'), PTCy_CD4, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/PTCy_CD8_shannons',type,'.png'), PTCy_CD8, width = 8, height = 4, dpi = 600)


ggsave(paste0(OUTPUT_PATH, '/Figure1ex/BothPTCy_CD4_shannons',type,'.pdf'), BothPTCy_CD4, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/BothPTCy_CD8_shannons',type,'.pdf'), BothPTCy_CD8, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/NoPTCy_CD4_shannons',type,'.pdf'), NoPTCy_CD4, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/NoPTCy_CD8_shannons',type,'.pdf'), NoPTCy_CD8, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/PTCy_CD4_shannons',type,'.pdf'), PTCy_CD4, width = 8, height = 4, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/PTCy_CD8_shannons',type,'.pdf'), PTCy_CD8, width = 8, height = 4, dpi = 600)

```

```{r}
data_CD48_all_expand_sel <- dplyr::full_join(data_CD48_all, clinical_data, by = 'PatientID')
data_CD48_all_expand_sel <- data_CD48_all_expand_sel[!is.na(data_CD48_all_expand_sel$cdr3_amino_acid),]

```


```{r, fig.height=10/1.1,fig.width = 18/1.1, warning = FALSE}
clinical_data <- read_excel(EXCEL_PATH, sheet = 'Patient Metadata cont.')

patient_data_all_clinic <- dplyr::inner_join(patient_data_all, clinical_data, by = "PatientID")%>%
  dplyr::inner_join(meta_data, by = "PatientID")%>%
  filter(strtoi(SampleID) > 3 | grepl("MLR|unstim", SampleID))%>%
  mutate(Onset = as.numeric(Onset), `EBV +` = as.numeric(`EBV +`),`Off Immunosuppresion` = as.numeric(`Off Immunosuppresion`), `CMV +` = as.numeric(`CMV +`),`HHV6 +` = as.numeric(`HHV6 +`), Systemic_Steroids = as.numeric(Systemic_Steroids) )
severe_cumulative <- patient_data_all_clinic[grepl('Severe',patient_data_all_clinic$GVHD_GRADE_1),]
mild_cumulative <- patient_data_all_clinic[grepl('Mild',patient_data_all_clinic$GVHD_GRADE_1),]
no_cumulative <- patient_data_all_clinic[grepl('No',patient_data_all_clinic$GVHD_GRADE_1),]
mild_cumulative <- mild_cumulative

no_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", no_cumulative$`Off Immunosuppresion`))
mild_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", mild_cumulative$`Off Immunosuppresion`))
severe_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", severe_cumulative$`Off Immunosuppresion`))

labels <- c("GHVD Onset", "Off Immunosuppresion", "EB Viremia", "CM Viremia", "HHV6", "Systemic Steroid")
##SEVERE

severe_cumulative_fig <- div_fig_pat(severe_cumulative, 'shannons.diversity', c('all'), 'PatientID', ylim = c(1,10))
severe_cumulative_fig_early <- severe_cumulative_fig[[1]]+
  labs(title = 'Severe GVHD', y = "Shannon's Diveristy")+
  theme(text = element_text(size = 36), plot.margin=unit(c(0,0,0,6.2), 'cm'))
severe_cumulative_fig_later <- severe_cumulative_fig[[2]]+
  theme(text = element_text(size = 36))
severe_meta_data_plot <- plot_metatime_cont(severe_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = severe_cumulative_fig[[3]])

severe_meta_data_plot[[1]] <- severe_meta_data_plot[[1]]+
  theme(text = element_text(size = 28))
severe_meta_data_plot[[2]] <- severe_meta_data_plot[[2]]+
  theme(text = element_text(size = 28))

  severe_comb <- plot_grid(plotlist = list(severe_cumulative_fig_early, severe_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

severe_meta_comb <- plot_grid(plotlist = list(severe_meta_data_plot[[1]], severe_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

Severe_meta_fig <- plot_grid(severe_comb, severe_meta_comb, nrow = 2, align = "hv", greedy = TRUE, rel_heights = c(1,.3))

##MIlD

mild_cumulative_fig <- div_fig_pat(mild_cumulative, 'shannons.diversity', c('all'), 'PatientID', ylim = c(1,10))
mild_cumulative_fig_early <- mild_cumulative_fig[[1]]+
  labs(title = 'Mild GVHD', y = "Shannon's Diveristy")+
  theme(text = element_text(size = 36), plot.margin=unit(c(0,0,0,6.2), 'cm'))
mild_cumulative_fig_later <- mild_cumulative_fig[[2]]+
  theme(text = element_text(size = 36))
mild_meta_data_plot <- plot_metatime_cont(mild_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = mild_cumulative_fig[[3]])

mild_meta_data_plot[[1]] <- mild_meta_data_plot[[1]]+
  theme(text = element_text(size = 28))

mild_meta_data_plot[[2]] <- mild_meta_data_plot[[2]]+
  theme(text = element_text(size = 28))

  mild_comb <- plot_grid(plotlist = list(mild_cumulative_fig_early, mild_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

 mild_meta_comb <- plot_grid(plotlist = list(mild_meta_data_plot[[1]], mild_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

Mild_meta_fig <- plot_grid(mild_comb, mild_meta_comb, nrow = 2, align = "hv", greedy = TRUE, rel_heights = c(1,.3))

##NO

no_cumulative_fig <- div_fig_pat(no_cumulative, 'shannons.diversity', c('all'), 'PatientID', ylim = c(1,10))
no_cumulative_fig_early <- no_cumulative_fig[[1]]+
  labs(title = 'No GVHD', y = "Shannon's Diveristy")+
  theme(text = element_text(size = 36), plot.margin=unit(c(0,0,0,6.2), 'cm'))
no_cumulative_fig_later <- no_cumulative_fig[[2]]+
  theme(text = element_text(size = 36))
no_meta_data_plot <- plot_metatime_cont(no_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = no_cumulative_fig[[3]])

no_meta_data_plot[[1]] <- no_meta_data_plot[[1]]+
  theme(text = element_text(size = 28))

no_meta_data_plot[[2]] <- no_meta_data_plot[[2]]+
  theme(text = element_text(size = 28))

  no_comb <- plot_grid(plotlist = list(no_cumulative_fig_early, no_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

  no_meta_comb <- plot_grid(plotlist = list(no_meta_data_plot[[1]], no_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

No_meta_fig <- plot_grid(no_comb, no_meta_comb, nrow = 2, align = "hv", greedy = TRUE, rel_heights = c(1,.3))

plot(Severe_meta_fig)
plot(Mild_meta_fig)
plot(No_meta_fig)


ggsave(paste0(OUTPUT_PATH, '/Figure1ex/severe_cumulative.png'), Severe_meta_fig, width = 18/1.1, height = 10/1.1, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/mild_cumuluative.png'), Mild_meta_fig, width = 18/1.1, height = 10, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/no_cumuluative.png'), No_meta_fig, width = 18/1.1, height = 10/1.1, dpi = 600)

ggsave(paste0(OUTPUT_PATH, '/Figure1ex/severe_cumulative.pdf'), Severe_meta_fig, width = 18/1.1, height = 10/1.1, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/mild_cumuluative.pdf'), Mild_meta_fig, width = 18/1.1, height = 10/1.1, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/no_cumuluative.pdf'), No_meta_fig, width = 18/1.1, height = 10/1.3, dpi = 600)

```

```{r, fig.height=10/1.1,fig.width = 18/1.1, warning = FALSE}
clinical_data <- read_excel(EXCEL_PATH, sheet = 'Patient Metadata cont.')

patient_data_all_clinic <- dplyr::inner_join(patient_data_all, clinical_data, by = "PatientID")%>%
  dplyr::inner_join(meta_data, by = "PatientID")%>%
  filter(strtoi(SampleID) > 3 | !grepl("MLR|unstim", SampleID))%>%
  mutate(Onset = as.numeric(Onset), `EBV +` = as.numeric(`EBV +`),`Off Immunosuppresion` = as.numeric(gsub("[^0-9]", "", `Off Immunosuppresion`)), `CMV +` = as.numeric(`CMV +`),`HHV6 +` = as.numeric(`HHV6 +`), Systemic_Steroids = as.numeric(Systemic_Steroids) )
severe_cumulative <- patient_data_all_clinic[grepl('Severe',patient_data_all_clinic$GVHD_GRADE_1),]
mild_cumulative <- patient_data_all_clinic[grepl('Mild',patient_data_all_clinic$GVHD_GRADE_1),]
no_cumulative <- patient_data_all_clinic[grepl('No',patient_data_all_clinic$GVHD_GRADE_1),]
mild_cumulative <- mild_cumulative

no_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", no_cumulative$`Off Immunosuppresion`))
mild_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", mild_cumulative$`Off Immunosuppresion`))
severe_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", severe_cumulative$`Off Immunosuppresion`))

labels <- c("GHVD Onset", "Off Immunosuppresion", "EBV Viremia", "CMV Viremia", "HHV6 Viremia", "Systemic Steroid")
##SEVERE

severe_cumulative_fig <- div_fig_pat(severe_cumulative,  'cum_freq', c('allo'), 'PatientID', ylim = c(0, 0.05))
severe_cumulative_fig_early <- severe_cumulative_fig[[1]]+
  labs(y = "Alloreactive Cumulative\n Frequency", title = 'Severe GVHD')+
  theme(text = element_text(size = 32), plot.margin=unit(c(0,0,0,5.2), 'cm'))
severe_cumulative_fig_later <- severe_cumulative_fig[[2]]+
  theme(text = element_text(size = 32))
severe_meta_data_plot <- plot_metatime_cont(severe_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = severe_cumulative_fig[[3]])

severe_meta_data_plot[[1]] <- severe_meta_data_plot[[1]]+
  theme(text = element_text(size = 26))+
  coord_cartesian(xlim = c(0,360))+
  scale_x_continuous(expand = expansion(mult = c(0,0)))

severe_meta_data_plot[[2]] <- severe_meta_data_plot[[2]]+
  theme(text = element_text(size = 26))+
  coord_cartesian(xlim = c(360,severe_cumulative_fig[[3]]))+
  scale_x_continuous(expand = expansion(mult = c(0,0)))

severe_comb <- plot_grid(plotlist = list(severe_cumulative_fig_early, severe_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))


severe_meta_comb <- plot_grid(plotlist = list(severe_meta_data_plot[[1]], severe_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

Severe_meta_fig <- plot_grid(severe_comb, severe_meta_comb, nrow = 2, greedy = TRUE, rel_heights = c(1,.3))


##Mild

mild_cumulative_fig <- div_fig_pat(mild_cumulative,  'cum_freq', c('allo'), 'PatientID', ylim = c(0, 0.05))
mild_cumulative_fig_early <- mild_cumulative_fig[[1]]+
  labs(y = "Alloreactive Cumulative\n Frequency", title = 'Mild GVHD')+
  theme(text = element_text(size = 32), plot.margin=unit(c(0,0,0,5.2), 'cm'))
mild_cumulative_fig_later <- mild_cumulative_fig[[2]]+
  theme(text = element_text(size = 32))
mild_meta_data_plot <- plot_metatime_cont(mild_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = mild_cumulative_fig[[3]])

mild_meta_data_plot[[1]] <- mild_meta_data_plot[[1]]+
  theme(text = element_text(size = 26))

mild_meta_data_plot[[2]] <- mild_meta_data_plot[[2]]+
  theme(text = element_text(size = 26))

mild_comb <- plot_grid(plotlist = list(mild_cumulative_fig_early, mild_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))


mild_meta_comb <- plot_grid(plotlist = list(mild_meta_data_plot[[1]], mild_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

Mild_meta_fig <- plot_grid(mild_comb, mild_meta_comb, nrow = 2, greedy = TRUE, rel_heights = c(1,.3))


##NO

no_cumulative_fig <- div_fig_pat(no_cumulative,  'cum_freq', c('allo'), 'PatientID', ylim = c(0, 0.05))
no_cumulative_fig_early <- no_cumulative_fig[[1]]+
  labs(y = "Alloreactive Cumulative\n Frequency", title = 'No GVHD')+
  theme(text = element_text(size = 32), plot.margin=unit(c(0,0,0,5.2), 'cm'))
no_cumulative_fig_later <- no_cumulative_fig[[2]]+
  theme(text = element_text(size = 32))
no_meta_data_plot <- plot_metatime_cont(no_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = no_cumulative_fig[[3]])

no_meta_data_plot[[1]] <- no_meta_data_plot[[1]]+
  theme(text = element_text(size = 26))

no_meta_data_plot[[2]] <- no_meta_data_plot[[2]]+
  theme(text = element_text(size = 26))

no_comb <- plot_grid(plotlist = list(no_cumulative_fig_early, no_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))


no_meta_comb <- plot_grid(plotlist = list(no_meta_data_plot[[1]], no_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

No_meta_fig <- plot_grid(no_comb, no_meta_comb, nrow = 2, greedy = TRUE, rel_heights = c(1,.3))


plot(Severe_meta_fig)
plot(Mild_meta_fig)
plot(No_meta_fig)

ggsave(paste0(OUTPUT_PATH, '/Figure1ex/severe_cumulative.png'), Severe_meta_fig, width = 18/1.1, height = 10/1.1, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/mild_cumuluative.png'), Mild_meta_fig, width = 18/1.1, height = 10/1.1, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/no_cumuluative.png'), No_meta_fig, width = 18/1.1, height = 10/1.1, dpi = 600)

ggsave(paste0(OUTPUT_PATH, '/Figure1/severe_cumulative.pdf'), Severe_meta_fig, width = 18/1.1, height = 10/1.3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1/mild_cumuluative.pdf'), Mild_meta_fig, width = 18/1.1, height = 10/1.3, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1/no_cumuluative.pdf'), No_meta_fig, width = 18/1.3, height = 7.5, dpi = 600)

write.csv(patient_data_all_clinic, file.path(OUTPUT_PATH, "PatientDataClinic.csv"))


```


```{r,fig.height=10,fig.width = 18, warning = FALSE}
clinical_data <- read_excel(EXCEL_PATH, sheet = 'Patient Metadata cont.')



data_CD48_all_expand_adj <- data_CD48_all%>%
  filter(templates !=0)%>%
  group_by(PatientID,timepoint)%>%
  summarise(n_clone = n())



patient_data_all_clinic <- dplyr::inner_join(data_CD48_all_expand_adj, clinical_data, by = "PatientID")%>%
  dplyr::inner_join(meta_data, by = "PatientID")%>%
  filter(strtoi(timepoint) > 3 | !grepl("MLR|unstim", timepoint))%>%
  mutate(Onset = as.numeric(Onset), `EBV +` = as.numeric(`EBV +`),`Off Immunosuppresion` = as.numeric(gsub("[^0-9]", "", `Off Immunosuppresion`)), `CMV +` = as.numeric(`CMV +`),`HHV6 +` = as.numeric(`HHV6 +`), Systemic_Steroids = as.numeric(Systemic_Steroids))%>%
mutate(GVHD_GRADE_1 = ifelse(grepl("Severe", GVHD_GRADE_1), "Severe", GVHD_GRADE_1), Rep_div = "allo", SampleID = timepoint)
severe_cumulative <- patient_data_all_clinic[grepl('Severe',patient_data_all_clinic$GVHD_GRADE_1),]
mild_cumulative <- patient_data_all_clinic[grepl('Mild',patient_data_all_clinic$GVHD_GRADE_1),]
no_cumulative <- patient_data_all_clinic[grepl('No',patient_data_all_clinic$GVHD_GRADE_1),]
mild_cumulative <- mild_cumulative

no_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", no_cumulative$`Off Immunosuppresion`))
mild_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", mild_cumulative$`Off Immunosuppresion`))
severe_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", severe_cumulative$`Off Immunosuppresion`))

labels <- c("GHVD Onset", "Off Immunosuppresion", "EBV Viremia", "CMV Viremia", "HHV6 Viremia", "Systemic Steroid")
##SEVERE

severe_cumulative_fig <- div_fig_pat(severe_cumulative,  'n_clone', c('allo'), 'PatientID', ylim = c(0, 2000))
severe_cumulative_fig_early <- severe_cumulative_fig[[1]]+
  labs(title = 'Severe GVHD', y = "# of Clones")+
  theme(text = element_text(size = 20), plot.margin=unit(c(0,0,0,5.1), 'cm'))+
  scale_y_continuous(trans = "log1p", labels = scales::number_format(accuracy = 0.01))
severe_cumulative_fig_later <- severe_cumulative_fig[[2]]+
  theme(text = element_text(size = 20))+
  scale_y_continuous(trans = "log1p", labels = scales::number_format(accuracy = 0.01))
severe_meta_data_plot <- plot_metatime_cont(severe_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = severe_cumulative_fig[[3]])

severe_meta_data_plot[[1]] <- severe_meta_data_plot[[1]]+
  theme(text = element_text(size = 20))+
  coord_cartesian(xlim = c(0,360))+
  scale_x_continuous(expand = expansion(mult = c(0,0)))

severe_meta_data_plot[[2]] <- severe_meta_data_plot[[2]]+
  theme(text = element_text(size = 20))+
  coord_cartesian(xlim = c(360,severe_cumulative_fig[[3]]))+
  scale_x_continuous(expand = expansion(mult = c(0,0)))

  severe_comb <- plot_grid(plotlist = list(severe_cumulative_fig_early, severe_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))


severe_meta_comb <- plot_grid(plotlist = list(severe_meta_data_plot[[1]], severe_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

Severe_meta_fig <- plot_grid(severe_comb, severe_meta_comb, nrow = 2, greedy = TRUE, rel_heights = c(1,.3))


##Mild

mild_cumulative_fig <- div_fig_pat(mild_cumulative,  'n_clone', c('allo'), 'PatientID', ylim = c(0, 2000))
mild_cumulative_fig_early <- mild_cumulative_fig[[1]]+
  labs(title = 'Mild GVHD', y = "# of Clones")+
  theme(text = element_text(size = 20), plot.margin=unit(c(0,0,0,5.1), 'cm'))+
  scale_y_continuous(trans = "log1p", labels = scales::number_format(accuracy = 0.01))
mild_cumulative_fig_later <- mild_cumulative_fig[[2]]+
  theme(text = element_text(size = 20))+
  scale_y_continuous(trans = "log1p", labels = scales::number_format(accuracy = 0.01))
mild_meta_data_plot <- plot_metatime_cont(mild_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = mild_cumulative_fig[[3]])

mild_meta_data_plot[[1]] <- mild_meta_data_plot[[1]]+
  theme(text = element_text(size = 20))

mild_meta_data_plot[[2]] <- mild_meta_data_plot[[2]]+
  theme(text = element_text(size = 20))

  mild_comb <- plot_grid(plotlist = list(mild_cumulative_fig_early, mild_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))


mild_meta_comb <- plot_grid(plotlist = list(mild_meta_data_plot[[1]], mild_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

Mild_meta_fig <- plot_grid(mild_comb, mild_meta_comb, nrow = 2, greedy = TRUE, rel_heights = c(1,.3))


##NO

no_cumulative_fig <- div_fig_pat(no_cumulative,  'n_clone', c('allo'), 'PatientID', ylim = c(0, 2000))
no_cumulative_fig_early <- no_cumulative_fig[[1]]+
  labs(title = 'No GVHD', y = "# of Clones")+
  theme(text = element_text(size = 20), plot.margin=unit(c(0,0,0,5.1), 'cm'))+
  scale_y_continuous(trans = "log1p", labels = scales::number_format(accuracy = 0.01))
no_cumulative_fig_later <- no_cumulative_fig[[2]]+
  theme(text = element_text(size = 20))+
  scale_y_continuous(trans = "log1p", labels = scales::number_format(accuracy = 0.01))
no_meta_data_plot <- plot_metatime_cont(no_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = no_cumulative_fig[[3]])

no_meta_data_plot[[1]] <- no_meta_data_plot[[1]]+
  theme(text = element_text(size = 20))

no_meta_data_plot[[2]] <- no_meta_data_plot[[2]]+
  theme(text = element_text(size = 20))




no_comb <- plot_grid(plotlist = list(no_cumulative_fig_early, no_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))


no_meta_comb <- plot_grid(plotlist = list(no_meta_data_plot[[1]], no_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

No_meta_fig <- plot_grid(no_comb, no_meta_comb, nrow = 2, greedy = TRUE, rel_heights = c(1,.3))


plot(Severe_meta_fig)
plot(Mild_meta_fig)
plot(No_meta_fig)

```

```{r, fig.height=10,fig.width = 18, warning = FALSE}
clinical_data <- read_excel(EXCEL_PATH, sheet = 'Patient Metadata cont.')

patient_data_all_clinic <- dplyr::inner_join(patient_data_all, clinical_data, by = "PatientID")%>%
  dplyr::inner_join(meta_data, by = "PatientID")%>%
  filter(strtoi(SampleID) > 3 | grepl("MLR|unstim", SampleID))%>%
  mutate(Onset = as.numeric(Onset), `EBV +` = as.numeric(`EBV +`),`Off Immunosuppresion` = as.numeric(`Off Immunosuppresion`), `CMV +` = as.numeric(`CMV +`),`HHV6 +` = as.numeric(`HHV6 +`), Systemic_Steroids = as.numeric(Systemic_Steroids) )
ptcy_cumulative <- patient_data_all_clinic[patient_data_all_clinic$PTCy == "PTCy",]
no_ptcy_cumulative <- patient_data_all_clinic[patient_data_all_clinic$PTCy == "No PTCy",]

no_ptcy_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", no_ptcy_cumulative$`Off Immunosuppresion`))
ptcy_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", ptcy_cumulative$`Off Immunosuppresion`))

labels <- c("GHVD Onset", "Off Immunosuppresion", "EB Viremia", "CM Viremia", "HHV6", "Systemic Steroid")
##ptcy

ptcy_cumulative_fig <- div_fig_pat(ptcy_cumulative, 'shannons.diversity', c('all'), 'PatientID', ylim = c(1,10))
ptcy_cumulative_fig_early <- ptcy_cumulative_fig[[1]]+
  labs(title = 'PTCy', y = "Shannon's Diveristy")+
  theme(text = element_text(size = 28), plot.margin=unit(c(0,0,0,7.3), 'cm'))
ptcy_cumulative_fig_later <- ptcy_cumulative_fig[[2]]+
  theme(text = element_text(size = 28))
ptcy_meta_data_plot <- plot_metatime_cont(ptcy_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = ptcy_cumulative_fig[[3]])

ptcy_meta_data_plot[[1]] <- ptcy_meta_data_plot[[1]]+
  theme(text = element_text(size = 28))

ptcy_meta_data_plot[[2]] <- ptcy_meta_data_plot[[2]]+
  theme(text = element_text(size = 28))

  ptcy_comb <- plot_grid(plotlist = list(ptcy_cumulative_fig_early, ptcy_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

ptcy_meta_comb <- plot_grid(plotlist = list(ptcy_meta_data_plot[[1]], ptcy_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

ptcy_meta_fig <- plot_grid(ptcy_comb, ptcy_meta_comb, nrow = 2, align = "hv", greedy = TRUE, rel_heights = c(1,.3))

##no_ptcy

no_ptcy_cumulative_fig <- div_fig_pat(no_ptcy_cumulative, 'shannons.diversity', c('all'), 'PatientID', ylim = c(1,10))
no_ptcy_cumulative_fig_early <- no_ptcy_cumulative_fig[[1]]+
  labs(title = 'No PTCy', y = "Shannon's Diveristy")+
  theme(text = element_text(size = 28), plot.margin=unit(c(0,0,0,7.3), 'cm'))
no_ptcy_cumulative_fig_later <- no_ptcy_cumulative_fig[[2]]+
  theme(text = element_text(size = 28))
no_ptcy_meta_data_plot <- plot_metatime_cont(no_ptcy_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = no_ptcy_cumulative_fig[[3]])

no_ptcy_meta_data_plot[[1]] <- no_ptcy_meta_data_plot[[1]]+
  theme(text = element_text(size = 28))

no_ptcy_meta_data_plot[[2]] <- no_ptcy_meta_data_plot[[2]]+
  theme(text = element_text(size = 28))

  no_ptcy_comb <- plot_grid(plotlist = list(no_ptcy_cumulative_fig_early, no_ptcy_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

 no_ptcy_meta_comb <- plot_grid(plotlist = list(no_ptcy_meta_data_plot[[1]], no_ptcy_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

no_ptcy_meta_fig <- plot_grid(no_ptcy_comb, no_ptcy_meta_comb, nrow = 2, align = "hv", greedy = TRUE, rel_heights = c(1,.3))


plot(ptcy_meta_fig)
plot(no_ptcy_meta_fig)


# ggsave(paste0(OUTPUT_PATH, '/Figure2ex/ptcy_cumulative.png'), ptcy_meta_fig, width = 18, height = 10, dpi = 600)
# ggsave(paste0(OUTPUT_PATH, '/Figure2ex/no_ptcy_cumuluative.png'), no_ptcy_meta_fig, width = 18, height = 10, dpi = 600)

# ggsave(paste0(OUTPUT_PATH, '/Figure2ex/ptcy_cumulative.pdf'), ptcy_meta_fig, width = 18, height = 10, dpi = 600)
# ggsave(paste0(OUTPUT_PATH, '/Figure2ex/no_ptcy_cumuluative.pdf'), no_ptcy_meta_fig, width = 18, height = 10, dpi = 600)

```

```{r, fig.height=10,fig.width = 18, warning = FALSE}
clinical_data <- read_excel(EXCEL_PATH, sheet = 'Patient Metadata cont.')

patient_data_all_clinic <- dplyr::inner_join(patient_data_all, clinical_data, by = "PatientID")%>%
  dplyr::inner_join(meta_data, by = "PatientID")%>%
  filter(strtoi(SampleID) > 3 | !grepl("MLR|unstim", SampleID))%>%
  mutate(Onset = as.numeric(Onset), `EBV +` = as.numeric(`EBV +`),`Off Immunosuppresion` = as.numeric(gsub("[^0-9]", "", `Off Immunosuppresion`)), `CMV +` = as.numeric(`CMV +`),`HHV6 +` = as.numeric(`HHV6 +`), Systemic_Steroids = as.numeric(Systemic_Steroids) )
ptcy_cumulative <- patient_data_all_clinic[patient_data_all_clinic$PTCy == "PTCy",]
no_ptcy_cumulative <- patient_data_all_clinic[patient_data_all_clinic$PTCy == "No PTCy",]

no_ptcy_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", no_ptcy_cumulative$`Off Immunosuppresion`))
ptcy_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", ptcy_cumulative$`Off Immunosuppresion`))

labels <- c("GHVD Onset", "Off Immunosuppresion", "EBV Viremia", "CMV Viremia", "HHV6 Viremia", "Systemic Steroid")
##ptcy

ptcy_cumulative_fig <- div_fig_pat(ptcy_cumulative,  'cum_freq', c('allo'), 'PatientID', ylim = c(0, 0.05))
ptcy_cumulative_fig_early <- ptcy_cumulative_fig[[1]]+
  labs(y = "Alloreactive Cumulative Frequency", title = 'PTCy')+
  theme(text = element_text(size = 20), plot.margin=unit(c(0,0,0,5.2), 'cm'))
ptcy_cumulative_fig_later <- ptcy_cumulative_fig[[2]]+
  theme(text = element_text(size = 20))
ptcy_meta_data_plot <- plot_metatime_cont(ptcy_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = ptcy_cumulative_fig[[3]])

ptcy_meta_data_plot[[1]] <- ptcy_meta_data_plot[[1]]+
  theme(text = element_text(size = 20))+
  coord_cartesian(xlim = c(0,360))+
  scale_x_continuous(expand = expansion(mult = c(0,0)))

ptcy_meta_data_plot[[2]] <- ptcy_meta_data_plot[[2]]+
  theme(text = element_text(size = 20))+
  coord_cartesian(xlim = c(360,ptcy_cumulative_fig[[3]]))+
  scale_x_continuous(expand = expansion(mult = c(0,0)))

ptcy_comb <- plot_grid(plotlist = list(ptcy_cumulative_fig_early, ptcy_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))


ptcy_meta_comb <- plot_grid(plotlist = list(ptcy_meta_data_plot[[1]], ptcy_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

ptcy_meta_fig <- plot_grid(ptcy_comb, ptcy_meta_comb, nrow = 2, greedy = TRUE, rel_heights = c(1,.3))


##no_ptcy

no_ptcy_cumulative_fig <- div_fig_pat(no_ptcy_cumulative,  'cum_freq', c('allo'), 'PatientID', ylim = c(0, 0.05))
no_ptcy_cumulative_fig_early <- no_ptcy_cumulative_fig[[1]]+
  labs(y = "Alloreactive Cumulative Frequency", title = 'No PTCy')+
  theme(text = element_text(size = 20), plot.margin=unit(c(0,0,0,5.2), 'cm'))
no_ptcy_cumulative_fig_later <- no_ptcy_cumulative_fig[[2]]+
  theme(text = element_text(size = 20))
no_ptcy_meta_data_plot <- plot_metatime_cont(no_ptcy_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = no_ptcy_cumulative_fig[[3]])

no_ptcy_meta_data_plot[[1]] <- no_ptcy_meta_data_plot[[1]]+
  theme(text = element_text(size = 20))

no_ptcy_meta_data_plot[[2]] <- no_ptcy_meta_data_plot[[2]]+
  theme(text = element_text(size = 20))

no_ptcy_comb <- plot_grid(plotlist = list(no_ptcy_cumulative_fig_early, no_ptcy_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))


no_ptcy_meta_comb <- plot_grid(plotlist = list(no_ptcy_meta_data_plot[[1]], no_ptcy_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

no_ptcy_meta_fig <- plot_grid(no_ptcy_comb, no_ptcy_meta_comb, nrow = 2, greedy = TRUE, rel_heights = c(1,.3))




plot(ptcy_meta_fig)
plot(no_ptcy_meta_fig)

ggsave(paste0(OUTPUT_PATH, '/Figure1ex/ptcy_cumulative.png'), ptcy_meta_fig, width = 18, height = 10, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1ex/no_ptcy_cumuluative.png'), no_ptcy_meta_fig, width = 18, height = 10, dpi = 600)

ggsave(paste0(OUTPUT_PATH, '/Figure1/ptcy_cumulative.pdf'), ptcy_meta_fig, width = 18, height = 10, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure1/no_ptcy_cumuluative.pdf'), no_ptcy_meta_fig, width = 18, height = 10, dpi = 600)

write.csv(patient_data_all_clinic, file.path(OUTPUT_PATH, "PatientDataClinic.csv"))


```


```{r,fig.height=10,fig.width = 18, warning = FALSE}
clinical_data <- read_excel(EXCEL_PATH, sheet = 'Patient Metadata cont.')



data_CD48_all_expand_adj <- data_CD48_all%>%
  filter(templates !=0)%>%
  group_by(PatientID,timepoint)%>%
  summarise(n_clone = n())



patient_data_all_clinic <- dplyr::inner_join(data_CD48_all_expand_adj, clinical_data, by = "PatientID")%>%
  dplyr::inner_join(meta_data, by = "PatientID")%>%
  filter(strtoi(timepoint) > 3 | !grepl("MLR|unstim", timepoint))%>%
  mutate(Onset = as.numeric(Onset), `EBV +` = as.numeric(`EBV +`),`Off Immunosuppresion` = as.numeric(gsub("[^0-9]", "", `Off Immunosuppresion`)), `CMV +` = as.numeric(`CMV +`),`HHV6 +` = as.numeric(`HHV6 +`), Systemic_Steroids = as.numeric(Systemic_Steroids))%>%
mutate(GVHD_GRADE_1 = ifelse(grepl("ptcy", GVHD_GRADE_1), "ptcy", GVHD_GRADE_1), Rep_div = "allo", SampleID = timepoint)
ptcy_cumulative <- patient_data_all_clinic[patient_data_all_clinic$PTCy == "PTCy",]
no_ptcy_cumulative <- patient_data_all_clinic[patient_data_all_clinic$PTCy == "No PTCy",]


no_ptcy_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", no_ptcy_cumulative$`Off Immunosuppresion`))
ptcy_cumulative$`Off Immunosuppresion` <- as.numeric(gsub("[^0-9]", "", ptcy_cumulative$`Off Immunosuppresion`))

labels <- c("GHVD Onset", "Off Immunosuppresion", "EBV Viremia", "CMV Viremia", "HHV6 Viremia", "Systemic Steroid")
##ptcy

ptcy_cumulative_fig <- div_fig_pat(ptcy_cumulative,  'n_clone', c('allo'), 'PatientID', ylim = c(0, 2000))
ptcy_cumulative_fig_early <- ptcy_cumulative_fig[[1]]+
  labs(title = 'PTCy', y = "# of Clones")+
  theme(text = element_text(size = 20), plot.margin=unit(c(0,0,0,5.1), 'cm'))+
  scale_y_continuous(trans = "log1p", labels = scales::number_format(accuracy = 1), breaks = c(0,10,100,1000))
ptcy_cumulative_fig_later <- ptcy_cumulative_fig[[2]]+
  theme(text = element_text(size = 20))+
  scale_y_continuous(trans = "log1p", labels = scales::number_format(accuracy = 1), breaks = c(0,10,100,1000))
ptcy_meta_data_plot <- plot_metatime_cont(ptcy_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = ptcy_cumulative_fig[[3]])

ptcy_meta_data_plot[[1]] <- ptcy_meta_data_plot[[1]]+
  theme(text = element_text(size = 20))+
  coord_cartesian(xlim = c(0,360))+
  scale_x_continuous(expand = expansion(mult = c(0,0)))

ptcy_meta_data_plot[[2]] <- ptcy_meta_data_plot[[2]]+
  theme(text = element_text(size = 20))+
  coord_cartesian(xlim = c(360,ptcy_cumulative_fig[[3]]))+
  scale_x_continuous(expand = expansion(mult = c(0,0)))

  ptcy_comb <- plot_grid(plotlist = list(ptcy_cumulative_fig_early, ptcy_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

ptcy_meta_comb <- plot_grid(plotlist = list(ptcy_meta_data_plot[[1]], ptcy_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

ptcy_meta_fig <- plot_grid(ptcy_comb, ptcy_meta_comb, nrow = 2, greedy = TRUE, rel_heights = c(1,.3))


##no_ptcy

no_ptcy_cumulative_fig <- div_fig_pat(no_ptcy_cumulative,  'n_clone', c('allo'), 'PatientID', ylim = c(0, 2000))
no_ptcy_cumulative_fig_early <- no_ptcy_cumulative_fig[[1]]+
  labs(title = 'No PTCy', y = "# of Clones")+
  theme(text = element_text(size = 20), plot.margin=unit(c(0,0,0,5.1), 'cm'))+
  scale_y_continuous(trans = "log1p", labels = scales::number_format(accuracy = 1), breaks = c(0,10,100,1000))
no_ptcy_cumulative_fig_later <- no_ptcy_cumulative_fig[[2]]+
  theme(text = element_text(size = 20))+
  scale_y_continuous(trans = "log1p", labels = scales::number_format(accuracy = 1), breaks = c(0,10,100,1000))
no_ptcy_meta_data_plot <- plot_metatime_cont(no_ptcy_cumulative, c("Onset", "Off Immunosuppresion", "EBV +", "CMV +", "HHV6 +", "Systemic_Steroids"), 'SampleID', label = labels, max_tp = no_ptcy_cumulative_fig[[3]])

no_ptcy_meta_data_plot[[1]] <- no_ptcy_meta_data_plot[[1]]+
  theme(text = element_text(size = 20))

no_ptcy_meta_data_plot[[2]] <- no_ptcy_meta_data_plot[[2]]+
  theme(text = element_text(size = 20))

  no_ptcy_comb <- plot_grid(plotlist = list(no_ptcy_cumulative_fig_early, no_ptcy_cumulative_fig_later), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))


no_ptcy_meta_comb <- plot_grid(plotlist = list(no_ptcy_meta_data_plot[[1]], no_ptcy_meta_data_plot[[2]]), ncol = 2, nrow = 1, hjust = 5, align = "h", rel_widths = c(1, .2))

no_ptcy_meta_fig <- plot_grid(no_ptcy_comb, no_ptcy_meta_comb, nrow = 2, greedy = TRUE, rel_heights = c(1,.3))


plot(ptcy_meta_fig)
plot(no_ptcy_meta_fig)

```

```{r}
clinical_data <- read_excel(EXCEL_PATH, sheet = 'Patient Metadata cont.')

patient_data_all_clinic <- dplyr::inner_join(patient_data_all, clinical_data, by = "PatientID")%>%
  dplyr::inner_join(meta_data, by = "PatientID")%>%
  filter(strtoi(SampleID) > 3 | grepl("MLR|unstim", SampleID))%>%
  mutate(Onset = as.numeric(Onset), `EBV +` = as.numeric(`EBV +`),`Off Immunosuppresion` = as.numeric(gsub("[^0-9]", "", `Off Immunosuppresion`)), `CMV +` = as.numeric(`CMV +`),`HHV6 +` = as.numeric(`HHV6 +`), Systemic_Steroids = as.numeric(Systemic_Steroids))%>%
  mutate(GVHD_GRADE_1 = ifelse(grepl("Severe",GVHD_GRADE_1), "Severe", GVHD_GRADE_1))%>%
  # mutate(PTCy = ifelse(grepl("PTCy", PTCy), "PTCy", "No PTCy"))%>%
  filter(!is.na(Onset))%>%
  group_by(PatientID, Onset)%>%
  mutate(tp_closest_onset = abs(strtoi(SampleID) - Onset))%>%
  slice_min(tp_closest_onset)%>%
  ungroup()%>%
  select(-tp_closest_onset)%>%
  filter(Rep_div == "allo")

data_CD48_all_expand_adj <- dplyr::full_join(data_CD48_all, clinical_data, by = 'PatientID')
data_CD48_all_expand_adj_tp <- data_CD48_all_expand_adj%>%
  select(timepoint, PatientID)%>%
  distinct()

data_CD48_all_expand_adj <- data_CD48_all_expand_adj%>%
  filter(templates !=0)%>%
  group_by(PatientID,timepoint,Onset, GVHD_GRADE_1, PTCy)%>%
  # mutate(PTCy = ifelse(grepl("PTCy", PTCy), "PTCy", "No PTCy"))%>%
  summarise(n_clone = n())%>%
  inner_join(data_CD48_all_expand_adj_tp, by = c("PatientID", "timepoint"))%>%
  replace_na(list(n_clone = 0))%>%
  filter(!is.na(Onset))%>%
  group_by(PatientID, Onset)%>%
  mutate(tp_closest_onset = abs(strtoi(timepoint) - Onset))%>%
  slice_min(tp_closest_onset)%>%
  ungroup()%>%
  select(-tp_closest_onset)%>%
  mutate(GVHD_GRADE_1 = ifelse(grepl("Severe", GVHD_GRADE_1), "Severe", GVHD_GRADE_1))

onset_plot_freq <- ggplot(patient_data_all_clinic, aes(x = PTCy, y = cum_freq, group = PTCy, fill = PTCy))+
  geom_boxplot()+
  geom_beeswarm()+
  stat_compare_means(comparisons = list(c("PTCy", "No PTCy")), method = "wilcox.test", method.args= list(exact = F), alternative = "two.sided", label = "p.format", hide.ns = TRUE)+
  scale_fill_manual(values = c( "#005A8F","#B85000")) +
  theme_pubr()

onset_plot_div <- ggplot(patient_data_all_clinic, aes(x = PTCy, y = shannons.diversity, fill = PTCy))+
  geom_boxplot()+
  geom_beeswarm()+
  stat_compare_means(comparisons = list(c("PTCy", "No PTCy")), method = "wilcox.test", method.args= list(exact = F), alternative = "two.sided", label = "p.format", hide.ns = TRUE)+
  scale_fill_manual(values = c( "#005A8F","#B85000")) +
  theme_pubr()

onset_plot_n <- ggplot(data_CD48_all_expand_adj, aes(x = PTCy, y = n_clone, fill = PTCy))+
  geom_boxplot()+
  geom_beeswarm()+
  stat_compare_means(comparisons = list(c("PTCy", "No PTCy")), method = "wilcox.test", method.args= list(exact = F), alternative = "two.sided", label = "p.format", hide.ns = TRUE)+
  scale_fill_manual(values = c( "#005A8F","#B85000")) +
  theme_pubr()
#Add to suplementary

plot(onset_plot_freq)
plot(onset_plot_div)
plot(onset_plot_n)
```

```{r}
# Calculate ratio of allo to nonallo frequency for each patient with timepoint 2, 3, or unstimulated
calculate_ratios <- function(data, patient_clinical_data, timepoints_to_include = c("2", "3")) {
  # Get unique patients with the specified timepoints
  patients <- unique(data$PatientID[data$timepoint %in% timepoints_to_include])
  timepoints_to_include = c("2", "3", "unstimulated")

  # Initialize results dataframe
  results <- data.frame(
    PatientID = character(),
    timepoint = character(),  # Changed to character to accommodate "unstimulated"
    allo_frequency = numeric(),
    nonallo_frequency = numeric(),
    ratio = numeric(),
    DonorType = character(),
    Disease = character(),
    PTCy = character(),
    GVHD_GRADE_1 = character(),
    stringsAsFactors = FALSE
  )

  # Calculate ratio for each patient and timepoint
  for (patient in patients) {
    for (tp in timepoints_to_include) {
      # Check if this patient has data for this timepoint
      if (nrow(data[data$PatientID == patient & data$timepoint == tp, ]) > 0) {
        # Calculate allo frequency
        allo_data <- data %>%
          filter(type == "allo" & timepoint == tp & PatientID == patient)
        allo_f <- sum(allo_data$frequency)

        # Calculate nonallo frequency
        nonallo_data <- data %>%
          filter(type == "nonallo" & timepoint == tp & PatientID == patient)
        nonallo_f <- sum(nonallo_data$frequency)

        # Calculate ratio (handle division by zero)
        if (nonallo_f > 0) {
          ratio <- allo_f / nonallo_f
        } else {
          ratio <- NA  # or could use Inf if you prefer
        }

        # Get clinical data for this patient
        patient_data <- patient_clinical_data[patient_clinical_data$PatientID == patient, ]

        # If patient exists in clinical data, add all information
        if (nrow(patient_data) > 0) {
          results <- rbind(results, data.frame(
            PatientID = patient,
            timepoint = tp,
            allo_frequency = allo_f,
            nonallo_frequency = nonallo_f,
            ratio = ratio,
            DonorType = patient_data$DonorType,
            Disease = patient_data$Disease,
            PTCy = patient_data$PTCy,
            GVHD_GRADE_1 = patient_data$GVHD_GRADE_1,
            stringsAsFactors = FALSE
          ))
        } else {
          # If patient doesn't exist in clinical data, add results without clinical info
          results <- rbind(results, data.frame(
            PatientID = patient,
            timepoint = tp,
            allo_frequency = allo_f,
            nonallo_frequency = nonallo_f,
            ratio = ratio,
            DonorType = NA,
            Disease = NA,
            PTCy = NA,
            GVHD_GRADE_1 = NA,
            stringsAsFactors = FALSE
          ))
        }
      }
    }
  }

  return(results)
}

# Use the function to get ratios with clinical information
ratio_results <- calculate_ratios(data_all_squished,meta_data_clin)

# Display results
print(ratio_results)

```
```{r}
ratio_results$timepoint_modified <- ifelse(ratio_results$timepoint %in% c("2", "3"), "2/3", as.character(ratio_results$timepoint))

ratio_results$grade_modified <- ifelse(ratio_results$GVHD_GRADE_1 %in% c("Unclassified/Severe"), "Severe", as.character(ratio_results$GVHD_GRADE_1))
ratio_results$timepoint_modified <- factor(ratio_results$timepoint_modified,
                                          levels = c("unstimulated", "2/3"))

early_plot_avg_freq <- ggplot(ratio_results[ratio_results$PatientID != "R090", ], aes(x = timepoint_modified, y = ratio, shape = PatientID))+
    geom_line(aes(group = PatientID, color = grade_modified), linewidth = 1.5)+
    geom_point(aes(color = GVHD_GRADE_1), size = 6)+
    scale_y_continuous(labels = scales::number_format(accuracy = 0.0001))+
    stat_compare_means(comparisons = list(c("unstimulated","2/3")), method = "wilcox.test", paired = TRUE, label = "p.format", hide.ns = FALSE, group.by = "PatientID", method.args = list(alternative ="less"), size = 6, label.y = quantile(ratio_results[ratio_results$PatientID != "R090", ]$ratio, probs = c(0.90), na.rm = TRUE))+
    scale_color_manual(values = c("#005A8F", "#B85000", "grey","yellow"))+
    # expand_limits(y = max(df_timepoint$cum_freq)+.05)+
    labs(x = "Timepoint", y = "Accumulative Frequency", title = "allo/nonallo", color = "GVHD Grade")+
    # coord_cartesian(ylim = c(0,0.4))+
    theme_minimal()+
    theme_pubr()+
    theme(legend.position = "none")
plot(early_plot_avg_freq)

ggsave(paste0(OUTPUT_PATH, '/Figure3/allovsnonallo.png'), early_plot_avg_freq,  height = 6, width=5, dpi = 600)

ggsave(paste0(OUTPUT_PATH, '/Figure3/allovsnonallo.pdf'), early_plot_avg_freq,  height = 6, width=5, dpi = 600)
ggsave(paste0(OUTPUT_PATH, '/Figure3/allovsnonallo.svg'), early_plot_avg_freq,  height = 6, width=5, dpi = 600)

```
```{r}

ratio_results_filtered <- ratio_results[ratio_results$timepoint %in% c('2','3'),]
ratio_results_filtered_un <- ratio_results[ratio_results$timepoint %in% c('unstimulated'),]
```
```{r}
ratio_results_filtered

```

```{r}
ratio_results_filtered_un
```
```{r}
# Assuming ratio_results_filtered contains the stimulated samples (timepoint 2 or 3)
# and ratio_results_filtered_un contains the matching unstimulated samples

# Calculate fold change
fold_change <- ratio_results_filtered$ratio / ratio_results_filtered_un$ratio

# Calculate log2 fold change
log2_fold_change <- log2(fold_change)

# Or in one step:
log2_fold_change <- log2(ratio_results_filtered$ratio / ratio_results_filtered_un$ratio)
median(log2_fold_change)
```
```{r}
log2_fold_change
```

```{}
```
